In [12]:
import pandas as pd

control_actions = pd.read_excel('/home/h604827/ControlActions/DATA/1071_pvlo_alarms_clustered_with_control_actions.xlsx', sheet_name='control_actions')
control_actions

,cluster_id,cluster_start,cluster_end,action_timing,action_direction,Source,Description,VT_Start,PrevValue,Value
0,1,2022-01-05 08:53:41.853,2022-01-05 09:33:33.105,before,decrease,03HIC_1141,OP,2022-01-05 08:40:59.871,100,98
1,1,2022-01-05 08:53:41.853,2022-01-05 09:33:33.105,before,decrease,03HIC_1141,OP,2022-01-05 08:41:09.258,98,96
2,1,2022-01-05 08:53:41.853,2022-01-05 09:33:33.105,before,decrease,03HIC_1141,OP,2022-01-05 08:41:10.655,96,94
3,1,2022-01-05 08:53:41.853,2022-01-05 09:33:33.105,before,decrease,03HIC_1141,OP,2022-01-05 08:41:11.558,94,92
4,1,2022-01-05 08:53:41.853,2022-01-05 09:33:33.105,before,no_change,03PIC_1013,MODE,2022-01-05 08:41:15.253,CAS,MAN
...,...,...,...,...,...,...,...,...,...,...
16089,539,2025-06-22 17:14:12.209,2025-06-22 17:14:56.205,before,decrease,03PIC_1013,OP,2025-06-22 17:03:51.554,72,70
16090,539,2025-06-22 17:14:12.209,2025-06-22 17:14:56.205,after,no_change,03FIC_3435,MODE,2025-06-22 17:19:11.717,MAN,NORMAL
16091,539,2025-06-22 17:14:12.209,2025-06-22 17:14:56.205,after,no_change,03PIC_1013,MODE,2025-06-22 17:19:37.402,MAN,NORMAL
16092,539,2025-06-22 17:14:12.209,2025-06-22 17:14:56.205,after,increase,03LIC_1071,SP,2025-06-22 17:27:43.207,40,42
16093,539,2025-06-22 17:14:12.209,2025-06-22 17:14:56.205,after,increase,03LIC_1071,SP,2025-06-22 17:29:11.555,42,43

## SP and OP value distributions
This section isolates SP and OP actions, normalizes signed numeric values before conversion, and creates separate summary tables for PrevValue and Value. Each table keeps OP statistics first, then SP statistics, includes the p05 to p95 common-range view, and sorts tags with available SP data to the top. If a tag has no SP actions in the sheet, its SP columns remain empty.

In [13]:
import re

import plotly.express as px
from IPython.display import display

value_cols = ['PrevValue', 'Value']
action_types = ['OP', 'SP']


def parse_action_value(value):
    if pd.isna(value):
        return float('nan')

    if isinstance(value, str):
        cleaned_value = re.sub(r'^([+-])\s+', r'\1', value.strip())
        return pd.to_numeric(cleaned_value, errors='coerce')

    return pd.to_numeric(value, errors='coerce')


tag_action_values = (
    control_actions.loc[
        control_actions['Description'].isin(action_types),
        ['cluster_id', 'Source', 'Description', 'action_timing', 'action_direction', 'VT_Start', *value_cols],
    ]
    .copy()
    .rename(columns={'Source': 'tag', 'Description': 'action_type'})
)

for col in value_cols:
    tag_action_values[col] = tag_action_values[col].apply(parse_action_value)

tag_action_values_long = (
    tag_action_values
    .melt(
        id_vars=['cluster_id', 'tag', 'action_type', 'action_timing', 'action_direction', 'VT_Start'],
        value_vars=value_cols,
        var_name='value_field',
        value_name='action_value',
    )
    .dropna(subset=['action_value'])
)

tag_action_values_long['value_field'] = pd.Categorical(
    tag_action_values_long['value_field'],
    categories=['PrevValue', 'Value'],
    ordered=True,
)

tag_order = (
    tag_action_values_long.groupby('tag')
    .size()
    .sort_values(ascending=False)
    .index
    .tolist()
)

tag_action_values_long.head()

,cluster_id,tag,action_type,action_timing,action_direction,VT_Start,value_field,action_value
0,1,03HIC_1141,OP,before,decrease,2022-01-05 08:40:59.871,PrevValue,100.0
1,1,03HIC_1141,OP,before,decrease,2022-01-05 08:41:09.258,PrevValue,98.0
2,1,03HIC_1141,OP,before,decrease,2022-01-05 08:41:10.655,PrevValue,96.0
3,1,03HIC_1141,OP,before,decrease,2022-01-05 08:41:11.558,PrevValue,94.0
4,1,03HIC_1141,OP,before,decrease,2022-01-05 08:41:24.584,PrevValue,92.0

In [14]:
distribution_summary = (
    tag_action_values_long
    .groupby(['tag', 'action_type', 'value_field'], observed=True)['action_value']
    .agg(
        count='size',
        mean='mean',
        std='std',
        min='min',
        p05=lambda s: s.quantile(0.05),
        q25=lambda s: s.quantile(0.25),
        median='median',
        q75=lambda s: s.quantile(0.75),
        p95=lambda s: s.quantile(0.95),
        max='max',
    )
    .reset_index()
    .sort_values(['tag', 'value_field', 'action_type'])
)

metric_cols = ['mean', 'std', 'min', 'p05', 'q25', 'median', 'q75', 'p95', 'max']
summary_stat_cols = ['count', *metric_cols]
distribution_summary[metric_cols] = distribution_summary[metric_cols].round(3)


def format_common_range(low_value, high_value):
    if pd.isna(low_value) or pd.isna(high_value):
        return pd.NA
    return f'[{low_value:.3f}, {high_value:.3f}]'



def build_value_summary_table(value_field):
    value_field_summary = distribution_summary.loc[
        distribution_summary['value_field'] == value_field,
        ['tag', 'action_type', *summary_stat_cols],
    ].copy()

    op_summary = (
        value_field_summary.loc[value_field_summary['action_type'] == 'OP']
        .drop(columns='action_type')
        .rename(columns={col: f'{col}_OP' for col in summary_stat_cols})
    )

    sp_summary = (
        value_field_summary.loc[value_field_summary['action_type'] == 'SP']
        .drop(columns='action_type')
        .rename(columns={col: f'{col}_SP' for col in summary_stat_cols})
    )

    summary_table = op_summary.merge(sp_summary, on='tag', how='outer')

    summary_table['common_range_OP'] = summary_table.apply(
        lambda row: format_common_range(row['p05_OP'], row['p95_OP']),
        axis=1,
    )
    summary_table['common_range_SP'] = summary_table.apply(
        lambda row: format_common_range(row['p05_SP'], row['p95_SP']),
        axis=1,
    )

    summary_table = (
        summary_table
        .assign(
            has_sp=summary_table['count_SP'].notna(),
            has_op=summary_table['count_OP'].notna(),
        )
        .sort_values(
            ['has_sp', 'has_op', 'count_SP', 'count_OP', 'tag'],
            ascending=[False, False, False, False, True],
            na_position='last',
        )
        .drop(columns=['has_sp', 'has_op'])
        .reset_index(drop=True)
    )

    ordered_cols = [
        'tag',
        *[f'{col}_OP' for col in summary_stat_cols],
        'common_range_OP',
        *[f'{col}_SP' for col in summary_stat_cols],
        'common_range_SP',
    ]
    return summary_table[ordered_cols]


prev_value_summary = build_value_summary_table('PrevValue')
value_summary = build_value_summary_table('Value')

print('PrevValue summary')
display(prev_value_summary[prev_value_summary['tag'].isin(['03LIC_1071', '03LIC_1016', '03PIC_1013'])])

print('Value summary')
display(value_summary[value_summary['tag'].isin(['03LIC_1071', '03LIC_1016', '03PIC_1013'])])

PrevValue summary

,tag,count_OP,mean_OP,std_OP,min_OP,p05_OP,q25_OP,median_OP,q75_OP,p95_OP,...,mean_SP,std_SP,min_SP,p05_SP,q25_SP,median_SP,q75_SP,p95_SP,max_SP,common_range_SP
1,03LIC_1071,794.0,42.958,18.311,-6.88,2.0,34.241,49.000,55.000,64.029,...,37.180,8.063,0.000,25.000,34.0,36.566,40.0,50.0,73.271,"[25.000, 50.000]"
3,03LIC_1016,335.0,10.348,14.728,-6.88,-5.0,0.000,5.000,16.000,40.000,...,38.288,9.306,8.954,23.692,35.0,38.000,42.0,50.0,84.853,"[23.692, 50.000]"
16,03PIC_1013,1834.0,61.624,11.971,0.00,45.0,54.000,60.806,70.336,80.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>

Value summary

,tag,count_OP,mean_OP,std_OP,min_OP,p05_OP,q25_OP,median_OP,q75_OP,p95_OP,...,mean_SP,std_SP,min_SP,p05_SP,q25_SP,median_SP,q75_SP,p95_SP,max_SP,common_range_SP
1,03LIC_1071,794.0,42.741,18.415,-6.88,2.000,34.098,49.000,55.0,64.000,...,37.340,6.169,10.0,28.0,35.0,38.0,40.00,45.0,60.0,"[28.000, 45.000]"
3,03LIC_1016,335.0,10.131,14.256,-6.88,-4.264,0.000,5.000,16.0,40.000,...,37.612,6.317,20.0,25.0,35.0,39.0,41.17,45.0,60.0,"[25.000, 45.000]"
16,03PIC_1013,1834.0,61.571,11.842,2.00,45.065,54.000,60.762,70.2,79.941,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>

In [15]:
distribution_fig = px.violin(
    tag_action_values_long,
    x='tag',
    y='action_value',
    color='value_field',
    facet_row='action_type',
    box=True,
    points=False,
    category_orders={
        'tag': tag_order,
        'action_type': ['OP', 'SP'],
        'value_field': ['PrevValue', 'Value'],
    },
    title='Per-tag distribution of PrevValue and Value for SP and OP actions',
)

distribution_fig.update_layout(height=900, violinmode='overlay')
distribution_fig.update_xaxes(tickangle=45)

distribution_fig

In [16]:
control_actions

,cluster_id,cluster_start,cluster_end,action_timing,action_direction,Source,Description,VT_Start,PrevValue,Value
0,1,2022-01-05 08:53:41.853,2022-01-05 09:33:33.105,before,decrease,03HIC_1141,OP,2022-01-05 08:40:59.871,100,98
1,1,2022-01-05 08:53:41.853,2022-01-05 09:33:33.105,before,decrease,03HIC_1141,OP,2022-01-05 08:41:09.258,98,96
2,1,2022-01-05 08:53:41.853,2022-01-05 09:33:33.105,before,decrease,03HIC_1141,OP,2022-01-05 08:41:10.655,96,94
3,1,2022-01-05 08:53:41.853,2022-01-05 09:33:33.105,before,decrease,03HIC_1141,OP,2022-01-05 08:41:11.558,94,92
4,1,2022-01-05 08:53:41.853,2022-01-05 09:33:33.105,before,no_change,03PIC_1013,MODE,2022-01-05 08:41:15.253,CAS,MAN
...,...,...,...,...,...,...,...,...,...,...
16089,539,2025-06-22 17:14:12.209,2025-06-22 17:14:56.205,before,decrease,03PIC_1013,OP,2025-06-22 17:03:51.554,72,70
16090,539,2025-06-22 17:14:12.209,2025-06-22 17:14:56.205,after,no_change,03FIC_3435,MODE,2025-06-22 17:19:11.717,MAN,NORMAL
16091,539,2025-06-22 17:14:12.209,2025-06-22 17:14:56.205,after,no_change,03PIC_1013,MODE,2025-06-22 17:19:37.402,MAN,NORMAL
16092,539,2025-06-22 17:14:12.209,2025-06-22 17:14:56.205,after,increase,03LIC_1071,SP,2025-06-22 17:27:43.207,40,42
16093,539,2025-06-22 17:14:12.209,2025-06-22 17:14:56.205,after,increase,03LIC_1071,SP,2025-06-22 17:29:11.555,42,43

In [17]:
direction_actions = (
    control_actions.loc[
        control_actions['Description'].isin(['SP', 'OP']),
        ['Source', 'Description', 'action_direction'],
    ]
    .copy()
    .rename(columns={'Source': 'tag'})
)

direction_actions['action_direction'] = (
    direction_actions['action_direction']
    .astype(str)
    .str.strip()
    .str.lower()
)

direction_summary = (
    direction_actions.loc[
        direction_actions['action_direction'].isin(['increase', 'decrease'])
    ]
    .groupby(['tag', 'action_direction'])
    .size()
    .unstack(fill_value=0)
    .reindex(columns=['increase', 'decrease'], fill_value=0)
    .rename(columns={
        'increase': 'increase_count',
        'decrease': 'decrease_count',
    })
    .reset_index()
)

direction_summary['total_actions'] = (
    direction_summary['increase_count'] + direction_summary['decrease_count']
)

direction_summary = direction_summary.sort_values(
    ['total_actions', 'increase_count', 'decrease_count', 'tag'],
    ascending=[False, False, False, True],
).reset_index(drop=True)

direction_summary

action_direction          tag  increase_count  decrease_count  total_actions
0                  03FIC_3435            1405             807           2212
1                  03PIC_1013             831            1000           1831
2                  03HIC_1151             735             928           1663
3                  03HIC_3100             515            1098           1613
4                  03LIC_1071             597             449           1046
5                  03HIC_3132             864             155           1019
6                  03HIC_1141             290             698            988
7                  03PIC_3131             206             458            664
8                  03LIC_1034             301             291            592
9                  03LIC_3153             402              99            501
10                 03FIC_3415             207             239            446
11                 03LIC_1016             245             155            400
12                 03FIC_1085             138              72            210
13                 03LIC_1085              58             150            208
14                 03LIC_3178             104              49            153
15                 03FIC_3172              40              99            139
16                 03TIC_1009             109              18            127
17                 03PIC_1068              66              60            126
18                03FIC_3435A             108              15            123
19                 03LIC_3408              61              36             97
20                03HIC_1092A              13              39             52
21                 03LIC_1097              12              37             49
22                 03LIC_1031              27              11             38
23                 03HIC_1183              16              19             35
24                 03LIC_1094              11              23             34
25                03HIC_1009B              20               3             23
26                03HIC_1009A               3              16             19
27                03HIC_1023A               6              11             17
28                 03TIC_1023               5               1              6
29                 03TIC_0027               1               0              1

In [20]:
import re
import numpy as np
from IPython.display import Markdown, display

pv_data_path = '/home/h604827/ControlActions/DATA/03LIC_1071_JAN_2026_filtered.parquet'
tags_of_interest = ['03LIC_1071', '03LIC_1016', '03PIC_1013']
action_type_order = ['OP', 'SP']
pv_reference_col = '03LIC_1071.PV'
pv_clip_min = 0.0
pv_clip_max = 100.0
pv_bin_width = 5.0


def parse_step_value(value):
    if pd.isna(value):
        return float('nan')

    if isinstance(value, str):
        cleaned_value = re.sub(r'^([+-])\s+', r'\1', value.strip())
        return pd.to_numeric(cleaned_value, errors='coerce')

    return pd.to_numeric(value, errors='coerce')


minute_pv_data = pd.read_parquet(pv_data_path)

if 'TimeStamp' in minute_pv_data.columns:
    pv_lookup = minute_pv_data[['TimeStamp', pv_reference_col]].copy()
else:
    pv_lookup = minute_pv_data[[pv_reference_col]].reset_index()
    pv_lookup = pv_lookup.rename(columns={pv_lookup.columns[0]: 'TimeStamp'})

pv_lookup['TimeStamp'] = pd.to_datetime(pv_lookup['TimeStamp'], errors='coerce')
pv_lookup[pv_reference_col] = pd.to_numeric(pv_lookup[pv_reference_col], errors='coerce')
pv_lookup = (
    pv_lookup
    .dropna(subset=['TimeStamp', pv_reference_col])
    .sort_values('TimeStamp')
)

pv_range_actions = (
    control_actions.loc[
        control_actions['Source'].isin(tags_of_interest)
        & control_actions['Description'].isin(action_type_order),
        ['Source', 'Description', 'VT_Start', 'PrevValue', 'Value'],
    ]
    .copy()
    .rename(columns={'Source': 'tag', 'Description': 'action_type'})
)

pv_range_actions['VT_Start'] = pd.to_datetime(pv_range_actions['VT_Start'], errors='coerce')
pv_range_actions['prev_value_num'] = pv_range_actions['PrevValue'].apply(parse_step_value)
pv_range_actions['value_num'] = pv_range_actions['Value'].apply(parse_step_value)
pv_range_actions['step_change'] = (
    pv_range_actions['value_num'] - pv_range_actions['prev_value_num']
)
pv_range_actions = pv_range_actions.dropna(subset=['VT_Start']).sort_values('VT_Start')

actions_with_1071_pv = pd.merge_asof(
    pv_range_actions,
    pv_lookup,
    left_on='VT_Start',
    right_on='TimeStamp',
    direction='backward',
    tolerance=pd.Timedelta('1min'),
).rename(columns={pv_reference_col: 'pv_1071'})

matched_actions_with_1071_pv = actions_with_1071_pv.dropna(subset=['pv_1071']).copy()

if matched_actions_with_1071_pv.empty:
    raise ValueError('No SP or OP actions matched to 03LIC_1071.PV within one minute.')

matched_actions_with_1071_pv['pv_1071'] = matched_actions_with_1071_pv['pv_1071'].clip(
    lower=pv_clip_min,
    upper=pv_clip_max,
)

pv_bin_edges = np.arange(pv_clip_min, pv_clip_max + pv_bin_width, pv_bin_width)
pv_bin_labels = [
    f'[{left:.1f}, {right:.1f})' if right < pv_clip_max else f'[{left:.1f}, {right:.1f}]'
    for left, right in zip(pv_bin_edges[:-1], pv_bin_edges[1:])
]
pv_values_for_binning = matched_actions_with_1071_pv['pv_1071'].where(
    matched_actions_with_1071_pv['pv_1071'] < pv_clip_max,
    np.nextafter(pv_clip_max, pv_clip_min),
)

matched_actions_with_1071_pv['pv_1071_range'] = pd.cut(
    pv_values_for_binning,
    bins=pv_bin_edges,
    labels=pv_bin_labels,
    include_lowest=True,
    right=False,
)

step_change_actions = matched_actions_with_1071_pv.dropna(subset=['step_change']).copy()
step_change_actions = step_change_actions.loc[
    step_change_actions['step_change'] != 0
].copy()

if step_change_actions.empty:
    raise ValueError('No numeric non-zero step changes were found for the selected SP and OP actions.')

step_change_actions['step_direction'] = np.where(
    step_change_actions['step_change'] > 0,
    'increase',
    'decrease',
)

step_change_stats_by_1071_pv_range = (
    step_change_actions
    .groupby(['tag', 'action_type', 'pv_1071_range'], observed=True)['step_change']
    .agg(
        step_change_count='size',
        min='min',
        q25=lambda s: s.quantile(0.25),
        mean='mean',
        median='median',
        q75=lambda s: s.quantile(0.75),
        max='max',
        std='std',
    )
    .reset_index()
)

step_stat_cols = ['min', 'q25', 'mean', 'median', 'q75', 'max', 'std']
step_change_stats_by_1071_pv_range[step_stat_cols] = (
    step_change_stats_by_1071_pv_range[step_stat_cols].round(3)
)
step_change_stats_by_1071_pv_range = step_change_stats_by_1071_pv_range.sort_values(
    ['tag', 'action_type', 'pv_1071_range']
).reset_index(drop=True)

direction_by_1071_pv_range = (
    step_change_actions
    .groupby(['tag', 'action_type', 'pv_1071_range', 'step_direction'], observed=True)
    .size()
    .unstack(fill_value=0)
    .reindex(columns=['increase', 'decrease'], fill_value=0)
    .rename(columns={
        'increase': 'increase_count',
        'decrease': 'decrease_count',
    })
    .reset_index()
)

direction_by_1071_pv_range['total_actions'] = (
    direction_by_1071_pv_range['increase_count'] + direction_by_1071_pv_range['decrease_count']
)
direction_by_1071_pv_range = direction_by_1071_pv_range.sort_values(
    ['tag', 'action_type', 'pv_1071_range']
).reset_index(drop=True)

op_step_change_stats_by_1071_pv_range = step_change_stats_by_1071_pv_range.loc[
    step_change_stats_by_1071_pv_range['action_type'] == 'OP'
]
sp_step_change_stats_by_1071_pv_range = step_change_stats_by_1071_pv_range.loc[
    step_change_stats_by_1071_pv_range['action_type'] == 'SP'
]
op_direction_by_1071_pv_range = direction_by_1071_pv_range.loc[
    direction_by_1071_pv_range['action_type'] == 'OP'
]
sp_direction_by_1071_pv_range = direction_by_1071_pv_range.loc[
    direction_by_1071_pv_range['action_type'] == 'SP'
]

step_change_tables = {}
direction_tables = {}

empty_step_change_table = pd.DataFrame(
    columns=['pv_1071_range', 'step_change_count', 'min', 'q25', 'mean', 'median', 'q75', 'max', 'std']
)
empty_direction_table = pd.DataFrame(
    columns=['pv_1071_range', 'increase_count', 'decrease_count', 'total_actions']
)

print(
    f"Matched {len(matched_actions_with_1071_pv)} of {len(pv_range_actions)} SP/OP actions to 03LIC_1071.PV "
    f"using the latest minute value at or before each action time after clipping to [{pv_clip_min:.0f}, {pv_clip_max:.0f}]."
)
print(
    f"{len(step_change_actions)} actions have numeric non-zero step changes after computing Value - PrevValue."
)
print('Step change is computed as Value - PrevValue. Negative values mean the operator reduced the setting.')

for tag in tags_of_interest:
    display(Markdown(f'## {tag}'))

    for action_type in action_type_order:
        step_table = (
            step_change_stats_by_1071_pv_range.loc[
                (step_change_stats_by_1071_pv_range['tag'] == tag)
                & (step_change_stats_by_1071_pv_range['action_type'] == action_type),
                ['pv_1071_range', 'step_change_count', 'min', 'q25', 'mean', 'median', 'q75', 'max', 'std'],
            ]
            .reset_index(drop=True)
        )
        direction_table = (
            direction_by_1071_pv_range.loc[
                (direction_by_1071_pv_range['tag'] == tag)
                & (direction_by_1071_pv_range['action_type'] == action_type),
                ['pv_1071_range', 'increase_count', 'decrease_count', 'total_actions'],
            ]
            .reset_index(drop=True)
        )

        if step_table.empty:
            step_table = empty_step_change_table.copy()
        if direction_table.empty:
            direction_table = empty_direction_table.copy()

        step_change_tables[(tag, action_type)] = step_table
        direction_tables[(tag, action_type)] = direction_table

        display(Markdown(f'### {action_type} step-change stats by clipped 03LIC_1071.PV range'))
        display(step_table)

        display(Markdown(f'### {action_type} increase and decrease counts by clipped 03LIC_1071.PV range'))
        display(direction_table)

Matched 3395 of 3407 SP/OP actions to 03LIC_1071.PV using the latest minute value at or before each action time after clipping to [0, 100].
3391 actions have numeric non-zero step changes after computing Value - PrevValue.
Step change is computed as Value - PrevValue. Negative values mean the operator reduced the setting.

## 03LIC_1071

### OP step-change stats by clipped 03LIC_1071.PV range

,pv_1071_range,step_change_count,min,q25,mean,median,q75,max,std
0,"[0.0, 5.0)",177,-38.708,2.00,1.521,2.0,2.00,50.000,6.504
1,"[5.0, 10.0)",33,-5.000,1.00,2.500,2.0,2.00,25.000,5.660
2,"[10.0, 15.0)",20,-5.000,-2.00,1.300,2.0,2.00,20.000,5.391
3,"[15.0, 20.0)",19,-5.000,-2.00,1.415,1.5,2.50,11.880,4.840
4,"[20.0, 25.0)",18,-2.000,-2.00,2.556,2.0,2.00,20.000,5.649
5,"[25.0, 30.0)",39,-29.244,-0.45,-0.737,0.1,0.10,35.000,9.642
6,"[30.0, 35.0)",46,-49.791,-0.10,-0.878,-0.1,0.10,5.000,7.471
7,"[35.0, 40.0)",62,-20.000,-2.00,-0.924,-0.1,-0.10,5.000,3.729
8,"[40.0, 45.0)",48,-7.303,-2.00,0.177,-0.1,2.00,10.000,3.314
9,"[45.0, 50.0)",32,-5.000,-2.00,0.417,2.0,2.00,9.635,2.772
10,"[50.0, 55.0)",33,-35.000,-2.00,-2.278,-2.0,-1.00,11.808,8.023
11,"[55.0, 60.0)",60,-31.037,-2.00,-1.156,-1.0,0.10,10.000,4.626
12,"[60.0, 65.0)",49,-19.190,-2.00,-1.683,-2.0,-1.00,5.719,3.486
13,"[65.0, 70.0)",31,-30.000,-2.00,-3.528,-2.0,-1.00,10.825,7.469
14,"[70.0, 75.0)",28,-50.000,-2.00,-2.958,1.5,2.00,6.000,11.635
15,"[75.0, 80.0)",8,-10.000,-2.00,-1.000,-2.0,-0.25,7.000,5.155
16,"[80.0, 85.0)",7,-4.000,-2.50,-2.429,-2.0,-2.00,-2.000,0.787
17,"[85.0, 90.0)",19,-21.651,-3.50,-3.034,-2.0,-2.00,10.000,6.582
18,"[90.0, 95.0)",17,-50.000,-2.00,-2.052,-2.0,-2.00,40.000,16.892
19,"[95.0, 100.0]",36,-15.000,1.75,0.583,2.0,2.00,5.000,4.108

### OP increase and decrease counts by clipped 03LIC_1071.PV range

step_direction  pv_1071_range  increase_count  decrease_count  total_actions
0                  [0.0, 5.0)             145              32            177
1                 [5.0, 10.0)              26               7             33
2                [10.0, 15.0)              12               8             20
3                [15.0, 20.0)              11               8             19
4                [20.0, 25.0)              12               6             18
5                [25.0, 30.0)              29              10             39
6                [30.0, 35.0)              21              25             46
7                [35.0, 40.0)              15              47             62
8                [40.0, 45.0)              16              32             48
9                [45.0, 50.0)              18              14             32
10               [50.0, 55.0)               8              25             33
11               [55.0, 60.0)              27              33             60
12               [60.0, 65.0)              10              39             49
13               [65.0, 70.0)               3              28             31
14               [70.0, 75.0)              15              13             28
15               [75.0, 80.0)               2               6              8
16               [80.0, 85.0)               0               7              7
17               [85.0, 90.0)               4              15             19
18               [90.0, 95.0)               3              14             17
19              [95.0, 100.0]              30               6             36

### SP step-change stats by clipped 03LIC_1071.PV range

,pv_1071_range,step_change_count,min,q25,mean,median,q75,max,std
0,"[0.0, 5.0)",9,-10.000,1.00,6.612,2.000,10.000,35.000,15.054
1,"[5.0, 10.0)",5,2.000,2.00,3.200,2.000,5.000,5.000,1.643
2,"[10.0, 15.0)",5,1.000,2.00,1.866,2.000,2.000,2.330,0.505
3,"[15.0, 20.0)",7,-2.000,-0.50,2.899,2.000,2.000,17.293,6.598
4,"[20.0, 25.0)",15,-2.000,-2.00,1.631,1.000,2.000,20.465,5.612
5,"[25.0, 30.0)",58,-8.000,0.01,1.412,1.497,2.000,10.338,2.492
6,"[30.0, 35.0)",24,-3.909,0.50,1.417,2.000,2.000,7.864,2.229
7,"[35.0, 40.0)",32,-2.689,0.01,0.409,0.437,1.616,2.000,1.399
8,"[40.0, 45.0)",29,-17.459,0.01,-0.564,0.010,0.010,5.000,3.555
9,"[45.0, 50.0)",14,-5.000,-2.00,-0.901,-1.500,1.550,3.000,2.441
10,"[50.0, 55.0)",17,-13.350,-2.00,-1.595,-0.902,0.010,0.440,3.210
11,"[55.0, 60.0)",23,-22.158,-2.00,-2.145,2.000,2.000,2.000,7.205
12,"[60.0, 65.0)",28,-20.907,-2.00,-1.814,-2.000,2.000,2.000,4.557
13,"[65.0, 70.0)",5,-5.000,-2.00,-2.600,-2.000,-2.000,-2.000,1.342
14,"[70.0, 75.0)",8,-34.271,-2.00,-5.034,-2.000,-1.000,2.000,11.951
15,"[75.0, 80.0)",2,-2.000,-2.00,-2.000,-2.000,-2.000,-2.000,0.000

### SP increase and decrease counts by clipped 03LIC_1071.PV range

step_direction pv_1071_range  increase_count  decrease_count  total_actions
0                 [0.0, 5.0)               7               2              9
1                [5.0, 10.0)               5               0              5
2               [10.0, 15.0)               5               0              5
3               [15.0, 20.0)               5               2              7
4               [20.0, 25.0)               9               6             15
5               [25.0, 30.0)              52               6             58
6               [30.0, 35.0)              20               4             24
7               [35.0, 40.0)              26               6             32
8               [40.0, 45.0)              24               5             29
9               [45.0, 50.0)               5               9             14
10              [50.0, 55.0)               8               9             17
11              [55.0, 60.0)              13              10             23
12              [60.0, 65.0)               8              20             28
13              [65.0, 70.0)               0               5              5
14              [70.0, 75.0)               2               6              8
15              [75.0, 80.0)               0               2              2

## 03LIC_1016

### OP step-change stats by clipped 03LIC_1071.PV range

,pv_1071_range,step_change_count,min,q25,mean,median,q75,max,std
0,"[0.0, 5.0)",193,-40.000,-2.000,0.347,2.00,2.000,30.000,7.301
1,"[5.0, 10.0)",18,-5.000,-1.750,2.874,4.50,5.269,10.000,4.769
2,"[10.0, 15.0)",11,-26.390,-2.000,0.055,-2.00,8.500,11.880,10.536
3,"[15.0, 20.0)",6,-2.000,-2.000,1.167,-0.50,1.750,10.000,4.665
4,"[20.0, 25.0)",7,-25.888,0.000,-1.556,2.00,3.500,6.000,11.032
5,"[25.0, 30.0)",14,-24.081,-5.000,-3.783,-2.00,0.440,7.000,8.410
6,"[30.0, 35.0)",6,-72.780,-12.043,-16.029,-2.00,-2.000,-2.000,28.314
7,"[35.0, 40.0)",9,-8.000,-2.000,-1.236,-2.00,-2.000,7.880,4.144
8,"[40.0, 45.0)",4,1.000,3.250,3.500,4.00,4.250,5.000,1.732
9,"[45.0, 50.0)",2,-10.000,-6.515,-3.030,-3.03,0.455,3.940,9.857
10,"[50.0, 55.0)",5,-2.000,-2.000,2.661,2.00,2.000,13.303,6.276
11,"[55.0, 60.0)",11,-8.331,-2.000,0.515,2.00,2.500,7.000,4.455
12,"[60.0, 65.0)",9,-15.000,-2.000,-0.366,-2.00,-2.000,30.000,12.519
13,"[65.0, 70.0)",1,-5.000,-5.000,-5.000,-5.00,-5.000,-5.000,NaN
14,"[70.0, 75.0)",11,-46.577,-6.000,-7.314,-2.00,-2.000,2.000,13.707
15,"[75.0, 80.0)",1,8.000,8.000,8.000,8.00,8.000,8.000,NaN
16,"[80.0, 85.0)",2,2.000,2.000,2.000,2.00,2.000,2.000,0.000
17,"[90.0, 95.0)",9,-1.880,2.000,1.569,2.00,2.000,2.000,1.293
18,"[95.0, 100.0]",15,-8.000,1.000,0.533,1.00,2.000,4.000,2.900

### OP increase and decrease counts by clipped 03LIC_1071.PV range

step_direction  pv_1071_range  increase_count  decrease_count  total_actions
0                  [0.0, 5.0)             116              77            193
1                 [5.0, 10.0)              11               7             18
2                [10.0, 15.0)               4               7             11
3                [15.0, 20.0)               3               3              6
4                [20.0, 25.0)               5               2              7
5                [25.0, 30.0)               4              10             14
6                [30.0, 35.0)               0               6              6
7                [35.0, 40.0)               2               7              9
8                [40.0, 45.0)               4               0              4
9                [45.0, 50.0)               1               1              2
10               [50.0, 55.0)               3               2              5
11               [55.0, 60.0)               7               4             11
12               [60.0, 65.0)               2               7              9
13               [65.0, 70.0)               0               1              1
14               [70.0, 75.0)               1              10             11
15               [75.0, 80.0)               1               0              1
16               [80.0, 85.0)               2               0              2
17               [90.0, 95.0)               8               1              9
18              [95.0, 100.0]              12               3             15

### SP step-change stats by clipped 03LIC_1071.PV range

,pv_1071_range,step_change_count,min,q25,mean,median,q75,max,std
0,"[0.0, 5.0)",38,-29.256,-1.00,-0.260,1.00,2.00,15.000,8.216
1,"[5.0, 10.0)",9,0.303,2.00,1.811,2.00,2.00,2.000,0.566
2,"[10.0, 15.0)",2,-14.120,-10.09,-6.060,-6.06,-2.03,2.000,11.398
3,"[20.0, 25.0)",10,-13.224,-1.75,0.432,0.75,1.75,16.046,7.069
4,"[25.0, 30.0)",18,-2.626,1.00,0.937,1.25,2.00,2.000,1.521
5,"[30.0, 35.0)",12,-2.000,1.00,1.530,2.00,2.00,5.000,1.745
6,"[35.0, 40.0)",4,-2.000,0.25,0.750,1.50,2.00,2.000,1.893
7,"[40.0, 45.0)",10,-18.611,-2.00,-2.461,-1.50,0.50,2.000,5.942
8,"[45.0, 50.0)",10,-7.271,-2.00,-0.061,-1.00,2.00,5.662,3.828
9,"[50.0, 55.0)",10,-3.692,-2.00,-0.769,-1.00,0.50,2.000,1.877
10,"[55.0, 60.0)",10,-44.853,-15.25,-10.419,-2.00,1.75,2.000,16.948
11,"[60.0, 65.0)",20,-5.000,-2.00,-0.500,-2.00,2.00,2.000,2.212
12,"[65.0, 70.0)",7,-2.000,-2.00,0.286,2.00,2.00,2.000,2.138
13,"[70.0, 75.0)",3,-2.000,-2.00,-0.667,-2.00,0.00,2.000,2.309

### SP increase and decrease counts by clipped 03LIC_1071.PV range

step_direction pv_1071_range  increase_count  decrease_count  total_actions
0                 [0.0, 5.0)              27              11             38
1                [5.0, 10.0)               9               0              9
2               [10.0, 15.0)               1               1              2
3               [20.0, 25.0)               6               4             10
4               [25.0, 30.0)              15               3             18
5               [30.0, 35.0)              10               2             12
6               [35.0, 40.0)               3               1              4
7               [40.0, 45.0)               3               7             10
8               [45.0, 50.0)               4               6             10
9               [50.0, 55.0)               3               7             10
10              [55.0, 60.0)               4               6             10
11              [60.0, 65.0)               8              12             20
12              [65.0, 70.0)               4               3              7
13              [70.0, 75.0)               1               2              3

## 03PIC_1013

### OP step-change stats by clipped 03LIC_1071.PV range

,pv_1071_range,step_change_count,min,q25,mean,median,q75,max,std
0,"[0.0, 5.0)",77,-2.000,-2.000,0.387,1.0,2.000,2.750,1.639
1,"[5.0, 10.0)",5,1.000,2.000,1.800,2.0,2.000,2.000,0.447
2,"[10.0, 15.0)",38,-2.000,-2.000,-0.727,-1.0,-0.100,2.000,1.212
3,"[15.0, 20.0)",58,-2.000,-0.954,-0.400,-0.1,-0.100,2.000,0.887
4,"[20.0, 25.0)",68,-2.000,-1.000,-0.252,-0.1,-0.100,2.000,1.076
5,"[25.0, 30.0)",81,-2.000,-2.000,-0.498,-0.1,0.100,2.000,1.346
6,"[30.0, 35.0)",219,-2.041,-1.000,-0.250,-0.1,0.100,4.000,1.198
7,"[35.0, 40.0)",396,-4.000,-0.100,-0.218,-0.1,0.100,2.022,1.141
8,"[40.0, 45.0)",289,-2.000,-0.100,0.174,-0.1,1.000,2.000,1.221
9,"[45.0, 50.0)",171,-2.000,-1.000,0.156,0.1,1.000,2.000,1.298
10,"[50.0, 55.0)",136,-2.000,-0.100,-0.157,-0.1,0.100,2.000,0.709
11,"[55.0, 60.0)",85,-2.000,0.100,-0.095,0.1,0.100,2.000,0.809
12,"[60.0, 65.0)",71,-2.000,0.100,0.030,0.1,0.100,2.000,0.761
13,"[65.0, 70.0)",69,-2.000,0.100,-0.071,0.1,0.100,1.000,0.621
14,"[70.0, 75.0)",18,-2.000,-0.100,0.112,-0.1,1.475,2.000,1.394
15,"[75.0, 80.0)",1,-2.000,-2.000,-2.000,-2.0,-2.000,-2.000,NaN
16,"[80.0, 85.0)",9,-0.100,-0.100,-0.100,-0.1,-0.100,-0.100,0.000
17,"[95.0, 100.0]",40,-2.000,2.000,1.725,2.0,2.000,3.000,0.751

### OP increase and decrease counts by clipped 03LIC_1071.PV range

step_direction  pv_1071_range  increase_count  decrease_count  total_actions
0                  [0.0, 5.0)              53              24             77
1                 [5.0, 10.0)               5               0              5
2                [10.0, 15.0)               7              31             38
3                [15.0, 20.0)               7              51             58
4                [20.0, 25.0)              14              54             68
5                [25.0, 30.0)              27              54             81
6                [30.0, 35.0)              81             138            219
7                [35.0, 40.0)             118             278            396
8                [40.0, 45.0)             122             167            289
9                [45.0, 50.0)             101              70            171
10               [50.0, 55.0)              65              71            136
11               [55.0, 60.0)              64              21             85
12               [60.0, 65.0)              65               6             71
13               [65.0, 70.0)              58              11             69
14               [70.0, 75.0)               5              13             18
15               [75.0, 80.0)               0               1              1
16               [80.0, 85.0)               0               9              9
17              [95.0, 100.0]              39               1             40

### SP step-change stats by clipped 03LIC_1071.PV range

Empty DataFrame
Columns: [pv_1071_range, step_change_count, min, q25, mean, median, q75, max, std]
Index: []

### SP increase and decrease counts by clipped 03LIC_1071.PV range

Empty DataFrame
Columns: [pv_1071_range, increase_count, decrease_count, total_actions]
Index: []

In [7]:
# Alarms based on 02FI_1000 levels
import pandas as pd
from IPython.display import display

LOWER_LIMIT_FI1000 = 8.386505779
UPPER_LIMIT_FI1000 = 8.630339925

alarm_workbook_path = '/home/h604827/ControlActions/DATA/1071_pvlo_alarms_clustered_with_control_actions.xlsx'
alarm_sheet_name = 'overlapping_alarms'
fallback_pv_data_path = '/home/h604827/ControlActions/DATA/03LIC_1071_JAN_2026_filtered.parquet'
fi1000_col = '02FI_1000.PV'
expansion_schedule = [0.0, 0.10, 0.20, 0.30]


def strip_timezone(datetime_series):
    if getattr(datetime_series.dt, 'tz', None) is not None:
        return datetime_series.dt.tz_localize(None)
    return datetime_series


if 'minute_pv_data' not in globals():
    minute_pv_data = pd.read_parquet(globals().get('pv_data_path', fallback_pv_data_path))

if fi1000_col not in minute_pv_data.columns:
    raise KeyError(f'{fi1000_col} was not found in the loaded PV/OP data.')

if 'TimeStamp' in minute_pv_data.columns:
    fi1000_series = minute_pv_data[['TimeStamp', fi1000_col]].copy()
    fi1000_series['TimeStamp'] = pd.to_datetime(fi1000_series['TimeStamp'], errors='coerce')
    fi1000_series = fi1000_series.dropna(subset=['TimeStamp'])
    fi1000_series['TimeStamp'] = strip_timezone(fi1000_series['TimeStamp'])
    fi1000_series = fi1000_series.set_index('TimeStamp')[fi1000_col]
else:
    fi1000_series = minute_pv_data[[fi1000_col]].copy().reset_index()
    fi1000_series = fi1000_series.rename(columns={fi1000_series.columns[0]: 'TimeStamp'})
    fi1000_series['TimeStamp'] = pd.to_datetime(fi1000_series['TimeStamp'], errors='coerce')
    fi1000_series = fi1000_series.dropna(subset=['TimeStamp'])
    fi1000_series['TimeStamp'] = strip_timezone(fi1000_series['TimeStamp'])
    fi1000_series = fi1000_series.set_index('TimeStamp')[fi1000_col]

fi1000_series = pd.to_numeric(fi1000_series, errors='coerce').sort_index()
fi1000_series = fi1000_series[~fi1000_series.index.duplicated(keep='last')]

overlapping_alarms = pd.read_excel(alarm_workbook_path, sheet_name=alarm_sheet_name).copy()
raw_alarm_count = len(overlapping_alarms)
required_alarm_cols = ['alarm_start', 'alarm_end']
missing_alarm_cols = [col for col in required_alarm_cols if col not in overlapping_alarms.columns]
if missing_alarm_cols:
    raise KeyError(
        f'Missing required columns in {alarm_sheet_name}: {missing_alarm_cols}'
    )

for col in required_alarm_cols:
    overlapping_alarms[col] = pd.to_datetime(overlapping_alarms[col], errors='coerce')
    overlapping_alarms[col] = strip_timezone(overlapping_alarms[col])

alarm_windows = overlapping_alarms.dropna(subset=required_alarm_cols).copy()
alarm_windows = alarm_windows.loc[alarm_windows['alarm_end'] >= alarm_windows['alarm_start']].copy()
alarm_windows = alarm_windows.reset_index(drop=True)
alarm_windows['alarm_id'] = alarm_windows.index + 1
alarm_windows['sample_start'] = alarm_windows['alarm_start'].dt.ceil('min')
alarm_windows['sample_end'] = alarm_windows['alarm_end'].dt.floor('min')

base_span = UPPER_LIMIT_FI1000 - LOWER_LIMIT_FI1000


def evaluate_alarm_window(sample_start, sample_end, lower_limit, upper_limit):
    if pd.isna(sample_start) or pd.isna(sample_end) or sample_end < sample_start:
        return pd.Series(
            {
                'expected_samples': 0,
                'observed_samples': 0,
                'full_coverage': False,
                'outside_limit_count': 0,
                'min_fi1000': float('nan'),
                'max_fi1000': float('nan'),
                'within_limits': False,
            }
        )

    window = fi1000_series.loc[sample_start:sample_end]
    expected_samples = int((sample_end - sample_start) / pd.Timedelta(minutes=1)) + 1
    observed_samples = len(window)
    valid_window = window.dropna()
    full_coverage = observed_samples == expected_samples and len(valid_window) == expected_samples

    if valid_window.empty:
        min_value = float('nan')
        max_value = float('nan')
        outside_limit_count = 0
    else:
        min_value = valid_window.min()
        max_value = valid_window.max()
        outside_limit_count = int(
            (~valid_window.between(lower_limit, upper_limit, inclusive='both')).sum()
        )

    within_limits = bool(full_coverage and outside_limit_count == 0)

    return pd.Series(
        {
            'expected_samples': expected_samples,
            'observed_samples': observed_samples,
            'full_coverage': full_coverage,
            'outside_limit_count': outside_limit_count,
            'min_fi1000': min_value,
            'max_fi1000': max_value,
            'within_limits': within_limits,
        }
    )


summary_rows = []
fi1000_alarm_pass_tables = {}

print(
    'Envelope expansion rule: add the stated percentage of the base FI_1000 span to both sides of the base limits.'
 )
print(f'Total rows in overlapping_alarms: {raw_alarm_count}')
print(f'Alarm windows with valid start/end timestamps: {len(alarm_windows)}')

for expansion_fraction in expansion_schedule:
    expansion_pct = int(expansion_fraction * 100)
    margin = base_span * expansion_fraction
    lower_limit = LOWER_LIMIT_FI1000 - margin
    upper_limit = UPPER_LIMIT_FI1000 + margin

    scenario_eval = alarm_windows.apply(
        lambda row: evaluate_alarm_window(
            row['sample_start'],
            row['sample_end'],
            lower_limit,
            upper_limit,
        ),
        axis=1,
    )

    scenario_results = pd.concat(
        [
            alarm_windows[['alarm_id', 'alarm_start', 'alarm_end', 'sample_start', 'sample_end']],
            scenario_eval,
        ],
        axis=1,
    )
    
    passing_alarms = scenario_results.loc[scenario_results['within_limits']].copy()
    passing_alarms['min_fi1000'] = passing_alarms['min_fi1000'].round(6)
    passing_alarms['max_fi1000'] = passing_alarms['max_fi1000'].round(6)
    fi1000_alarm_pass_tables[expansion_pct] = passing_alarms[
        ['alarm_id', 'alarm_start', 'alarm_end', 'min_fi1000', 'max_fi1000', 'expected_samples']
    ].reset_index(drop=True)

    passing_alarm_count = len(passing_alarms)
    total_alarm_count = len(scenario_results)
    full_coverage_alarm_count = int(scenario_results['full_coverage'].sum())

    summary_rows.append(
        {
            'scenario': 'base_limits' if expansion_pct == 0 else f'base_plus_{expansion_pct}pct',
            'expansion_pct': expansion_pct,
            'lower_limit': round(lower_limit, 6),
            'upper_limit': round(upper_limit, 6),
            'passing_alarm_count': passing_alarm_count,
            'total_alarm_count': total_alarm_count,
            'passing_alarm_pct': round(100 * passing_alarm_count / total_alarm_count, 2),
            'full_coverage_alarm_count': full_coverage_alarm_count,
            'not_full_coverage_alarm_count': total_alarm_count - full_coverage_alarm_count,
        }
    )

fi1000_alarm_envelope_summary = pd.DataFrame(summary_rows)
display(fi1000_alarm_envelope_summary)

for expansion_pct in [0, 10, 20, 30]:
    passing_alarms = fi1000_alarm_pass_tables[expansion_pct]
    scenario_label = 'Base limits' if expansion_pct == 0 else f'Base limits + {expansion_pct}% expansion'
    print(
        f'\n{scenario_label}: {len(passing_alarms)} alarms stay within the evaluated FI_1000 limits for the full alarm duration.'
    )
    display(passing_alarms)

Envelope expansion rule: add the stated percentage of the base FI_1000 span to both sides of the base limits.
Total rows in overlapping_alarms: 539
Alarm windows with valid start/end timestamps: 539

,scenario,expansion_pct,lower_limit,upper_limit,passing_alarm_count,total_alarm_count,passing_alarm_pct,full_coverage_alarm_count,not_full_coverage_alarm_count
0,base_limits,0,8.386506,8.630340,57,539,10.58,528,11
1,base_plus_10pct,10,8.362122,8.654723,80,539,14.84,528,11
2,base_plus_20pct,20,8.337739,8.679107,103,539,19.11,528,11
3,base_plus_30pct,30,8.313356,8.703490,122,539,22.63,528,11

Base limits: 57 alarms stay within the evaluated FI_1000 limits for the full alarm duration.

,alarm_id,alarm_start,alarm_end,min_fi1000,max_fi1000,expected_samples
0,171,2023-05-02 04:42:34.805,2023-05-02 04:49:03.810,8.547328,8.611371,7
1,200,2023-08-09 13:26:54.004,2023-08-09 13:33:46.004,8.418064,8.496234,7
2,201,2023-08-10 16:58:00.004,2023-08-10 17:05:25.004,8.491291,8.620660,7
3,209,2023-10-25 01:45:14.104,2023-10-25 01:58:30.353,8.591278,8.591731,13
4,210,2023-10-25 02:46:07.104,2023-10-25 02:55:15.102,8.589126,8.589428,9
5,211,2023-10-25 03:56:16.104,2023-10-25 04:11:40.102,8.586257,8.586785,15
6,218,2024-01-02 05:50:15.102,2024-01-02 06:10:40.154,8.408764,8.603221,20
7,226,2024-01-05 11:01:11.952,2024-01-05 11:07:29.953,8.388277,8.490507,6
8,228,2024-01-05 17:21:03.352,2024-01-05 17:24:44.357,8.411674,8.461634,3
9,230,2024-01-06 02:17:57.203,2024-01-06 02:22:53.201,8.443940,8.458315,5
10,234,2024-01-06 11:01:40.353,2024-01-06 11:05:59.354,8.489911,8.518058,4
11,235,2024-01-06 17:59:45.404,2024-01-06 18:04:41.404,8.535021,8.583914,5
12,241,2024-01-07 04:02:09.352,2024-01-07 04:05:14.354,8.471346,8.509773,3
13,244,2024-01-09 06:16:26.303,2024-01-09 06:22:08.557,8.498920,8.597966,6
14,245,2024-01-10 18:56:12.053,2024-01-10 19:01:05.302,8.543817,8.598170,5
15,250,2024-01-18 09:56:35.753,2024-01-18 10:05:48.004,8.413552,8.528256,9
16,251,2024-01-19 22:46:09.156,2024-01-19 22:50:02.153,8.491180,8.569678,4
17,253,2024-01-21 08:09:47.602,2024-01-21 08:14:17.602,8.432138,8.523184,5
18,290,2024-04-18 22:28:26.855,2024-04-18 22:31:28.854,8.522134,8.565679,3
19,293,2024-04-22 16:29:38.903,2024-04-22 16:35:11.903,8.397555,8.522829,6
20,301,2024-04-28 16:42:51.152,2024-04-28 16:47:25.152,8.490509,8.519918,5
21,302,2024-04-30 16:03:27.603,2024-04-30 16:10:37.605,8.504632,8.549996,7
22,307,2024-05-07 14:24:02.503,2024-05-07 14:30:40.304,8.509695,8.537422,6
23,317,2024-05-10 01:58:05.003,2024-05-10 02:03:02.006,8.464891,8.543230,5
24,318,2024-05-10 02:35:03.253,2024-05-10 02:38:47.253,8.427602,8.459361,3
25,320,2024-05-11 00:21:56.154,2024-05-11 00:26:07.404,8.445528,8.579811,5
26,326,2024-05-12 02:15:26.554,2024-05-12 02:18:35.555,8.572324,8.601069,3
27,329,2024-05-17 12:39:04.003,2024-05-17 12:41:45.502,8.504373,8.570893,2
28,330,2024-05-18 14:18:53.054,2024-05-18 14:22:42.304,8.517761,8.594234,4
29,331,2024-05-21 06:14:16.153,2024-05-21 06:18:05.154,8.401290,8.525164,4
30,347,2024-06-04 14:27:22.352,2024-06-04 14:30:01.102,8.498762,8.551628,3
31,348,2024-06-06 13:11:55.304,2024-06-06 13:16:26.309,8.450489,8.517866,5
32,356,2024-06-12 11:49:51.252,2024-06-12 11:54:30.754,8.442128,8.489947,5
33,363,2024-06-16 10:29:23.952,2024-06-16 10:50:15.752,8.388656,8.621482,21
34,364,2024-06-16 15:31:40.955,2024-06-16 15:34:04.454,8.426075,8.455358,3
35,377,2024-06-24 10:55:24.356,2024-06-24 10:57:47.103,8.510852,8.518906,2
36,382,2024-06-29 11:20:05.154,2024-06-29 11:22:15.153,8.520190,8.579774,2
37,411,2024-08-25 15:45:50.702,2024-08-25 16:07:19.704,8.406747,8.568139,22
38,413,2024-08-27 04:52:43.652,2024-08-27 04:56:43.653,8.519086,8.591123,4
39,415,2024-08-29 07:18:29.452,2024-08-29 07:21:03.452,8.546250,8.586321,3
40,418,2024-09-07 12:29:45.003,2024-09-07 12:34:14.002,8.487750,8.516940,5
41,422,2024-09-16 04:33:58.804,2024-09-16 04:37:53.851,8.541741,8.574946,4
42,428,2024-09-21 05:57:24.354,2024-09-21 06:01:06.355,8.508754,8.608490,4
43,430,2024-09-22 00:43:50.101,2024-09-22 00:46:26.353,8.506560,8.604015,3
44,435,2024-10-06 03:17:12.555,2024-10-06 03:19:29.556,8.540176,8.548642,2
45,437,2024-10-11 23:25:08.204,2024-10-11 23:27:46.452,8.452864,8.496618,2
46,443,2024-11-14 14:03:02.402,2024-11-14 14:06:22.403,8.566986,8.594074,3
47,474,2025-01-08 06:34:40.425,2025-01-08 06:38:32.010,8.421060,8.500828,4
48,478,2025-01-09 07:12:33.384,2025-01-09 07:16:55.649,8.544545,8.611132,4
49,482,2025-01-14 06:35:00.639,2025-01-14 06:38:26.242,8.389374,8.419071,3
50,486,2025-01-16 10:34:54.364,2025-01-16 10:36:05.492,8.595736,8.627324,2
51,487,2025-01-16 11:07:26.293,2025-01-16 11:08:34.304,8.628880,8.628880,1
52,490,2025-04-19 17:22:41.581,2025-04-19 17:23:50.656,8.477488,8.477488,1
53,492,2025-04-20 07:29:40.425,2025-04-20 07:35:44.424,8.392848,8.540930,6
54,515,2025-05-21 14:17:53.579,2025-05-21 14:18:37.723,8.553716,8.553716,1
55,528,2025-06-17 17:30:50.107,2025-06-17 17:31:59.223,8.540364,8.540364,1
56,532,2025-06-19 12:31:42.504,2025-06-19 12:32:23.198,8.397397,8.397397,1

Base limits + 10% expansion: 80 alarms stay within the evaluated FI_1000 limits for the full alarm duration.

,alarm_id,alarm_start,alarm_end,min_fi1000,max_fi1000,expected_samples
0,171,2023-05-02 04:42:34.805,2023-05-02 04:49:03.810,8.547328,8.611371,7
1,172,2023-05-02 06:11:50.852,2023-05-02 06:18:34.852,8.482380,8.637196,7
2,176,2023-05-21 00:05:56.808,2023-05-21 00:11:22.804,8.567216,8.632663,6
3,200,2023-08-09 13:26:54.004,2023-08-09 13:33:46.004,8.418064,8.496234,7
4,201,2023-08-10 16:58:00.004,2023-08-10 17:05:25.004,8.491291,8.620660,7
...,...,...,...,...,...,...
75,492,2025-04-20 07:29:40.425,2025-04-20 07:35:44.424,8.392848,8.540930,6
76,515,2025-05-21 14:17:53.579,2025-05-21 14:18:37.723,8.553716,8.553716,1
77,528,2025-06-17 17:30:50.107,2025-06-17 17:31:59.223,8.540364,8.540364,1
78,532,2025-06-19 12:31:42.504,2025-06-19 12:32:23.198,8.397397,8.397397,1
79,535,2025-06-21 22:15:17.359,2025-06-21 22:16:18.517,8.642810,8.642810,1

Base limits + 20% expansion: 103 alarms stay within the evaluated FI_1000 limits for the full alarm duration.

,alarm_id,alarm_start,alarm_end,min_fi1000,max_fi1000,expected_samples
0,171,2023-05-02 04:42:34.805,2023-05-02 04:49:03.810,8.547328,8.611371,7
1,172,2023-05-02 06:11:50.852,2023-05-02 06:18:34.852,8.482380,8.637196,7
2,176,2023-05-21 00:05:56.808,2023-05-21 00:11:22.804,8.567216,8.632663,6
3,200,2023-08-09 13:26:54.004,2023-08-09 13:33:46.004,8.418064,8.496234,7
4,201,2023-08-10 16:58:00.004,2023-08-10 17:05:25.004,8.491291,8.620660,7
...,...,...,...,...,...,...
98,515,2025-05-21 14:17:53.579,2025-05-21 14:18:37.723,8.553716,8.553716,1
99,517,2025-05-22 12:13:57.733,2025-05-22 12:15:25.990,8.621990,8.674137,2
100,528,2025-06-17 17:30:50.107,2025-06-17 17:31:59.223,8.540364,8.540364,1
101,532,2025-06-19 12:31:42.504,2025-06-19 12:32:23.198,8.397397,8.397397,1
102,535,2025-06-21 22:15:17.359,2025-06-21 22:16:18.517,8.642810,8.642810,1

Base limits + 30% expansion: 122 alarms stay within the evaluated FI_1000 limits for the full alarm duration.

,alarm_id,alarm_start,alarm_end,min_fi1000,max_fi1000,expected_samples
0,116,2022-12-08 07:59:18.355,2022-12-08 08:06:23.353,8.328461,8.422258,7
1,171,2023-05-02 04:42:34.805,2023-05-02 04:49:03.810,8.547328,8.611371,7
2,172,2023-05-02 06:11:50.852,2023-05-02 06:18:34.852,8.482380,8.637196,7
3,176,2023-05-21 00:05:56.808,2023-05-21 00:11:22.804,8.567216,8.632663,6
4,178,2023-06-04 14:05:18.855,2023-06-04 14:15:02.406,8.333061,8.495438,10
...,...,...,...,...,...,...
117,517,2025-05-22 12:13:57.733,2025-05-22 12:15:25.990,8.621990,8.674137,2
118,528,2025-06-17 17:30:50.107,2025-06-17 17:31:59.223,8.540364,8.540364,1
119,531,2025-06-18 16:53:59.501,2025-06-18 16:54:47.382,8.336717,8.336717,1
120,532,2025-06-19 12:31:42.504,2025-06-19 12:32:23.198,8.397397,8.397397,1
121,535,2025-06-21 22:15:17.359,2025-06-21 22:16:18.517,8.642810,8.642810,1

In [9]:
# Most operated tags for alarms within the FI_1000 30% expansion band
import pandas as pd
from IPython.display import display

target_expansion_fraction = 0.30
target_expansion_pct = int(target_expansion_fraction * 100)
target_margin = base_span * target_expansion_fraction
target_lower_limit = LOWER_LIMIT_FI1000 - target_margin
target_upper_limit = UPPER_LIMIT_FI1000 + target_margin

fi1000_30pct_eval = alarm_windows.apply(
    lambda row: evaluate_alarm_window(
        row['sample_start'],
        row['sample_end'],
        target_lower_limit,
        target_upper_limit,
    ),
    axis=1,
 )

fi1000_30pct_results = pd.concat(
    [
        alarm_windows[['alarm_id', 'alarm_start', 'alarm_end', 'sample_start', 'sample_end']],
        fi1000_30pct_eval,
    ],
    axis=1,
 )

fi1000_30pct_passing_alarms = fi1000_30pct_results.loc[
    fi1000_30pct_results['within_limits']
].copy()
fi1000_30pct_passing_alarms['min_fi1000'] = fi1000_30pct_passing_alarms['min_fi1000'].round(6)
fi1000_30pct_passing_alarms['max_fi1000'] = fi1000_30pct_passing_alarms['max_fi1000'].round(6)

if 'control_actions' not in globals():
    control_actions = pd.read_excel(
        alarm_workbook_path,
        sheet_name='control_actions',
    )

filtered_control_actions = control_actions.copy()
for col in ['cluster_start', 'cluster_end', 'VT_Start']:
    filtered_control_actions[col] = pd.to_datetime(filtered_control_actions[col], errors='coerce')
    filtered_control_actions[col] = strip_timezone(filtered_control_actions[col])

qualified_alarm_lookup = fi1000_30pct_passing_alarms[
    ['alarm_id', 'alarm_start', 'alarm_end']
].rename(columns={'alarm_start': 'cluster_start', 'alarm_end': 'cluster_end'})

qualified_alarm_actions = filtered_control_actions.merge(
    qualified_alarm_lookup,
    on=['cluster_start', 'cluster_end'],
    how='inner',
 )

qualified_alarm_actions = qualified_alarm_actions.loc[
    qualified_alarm_actions['Description'].isin(['OP', 'SP'])
].copy()

if qualified_alarm_actions.empty:
    raise ValueError(
        'No OP/SP control-action rows were matched to the alarms inside the FI_1000 30% expansion band.'
    )

action_count_by_tag = (
    qualified_alarm_actions.groupby(['Description', 'Source'])
    .agg(
        action_count=('Source', 'size'),
        unique_alarm_count=('alarm_id', 'nunique'),
    )
    .reset_index()
    .rename(columns={'Description': 'action_type', 'Source': 'tag'})
 )

timing_breakdown = (
    qualified_alarm_actions.groupby(['Description', 'Source', 'action_timing'])
    .size()
    .unstack(fill_value=0)
    .reset_index()
    .rename(columns={'Description': 'action_type', 'Source': 'tag'})
 )

tag_operation_summary = action_count_by_tag.merge(
    timing_breakdown,
    on=['action_type', 'tag'],
    how='left',
 )

sort_cols = ['action_count', 'unique_alarm_count', 'tag']
op_most_operated_tags = (
    tag_operation_summary.loc[tag_operation_summary['action_type'] == 'OP']
    .sort_values(sort_cols, ascending=[False, False, True])
    .reset_index(drop=True)
 )
sp_most_operated_tags = (
    tag_operation_summary.loc[tag_operation_summary['action_type'] == 'SP']
    .sort_values(sort_cols, ascending=[False, False, True])
    .reset_index(drop=True)
 )

print(
    f'FI_1000 30% expansion band: [{target_lower_limit:.6f}, {target_upper_limit:.6f}]'
 )
print(
    f'{len(fi1000_30pct_passing_alarms)} alarms stay inside this band for the full alarm duration.'
 )
print(
    f"{qualified_alarm_actions['alarm_id'].nunique()} of those alarms have matched OP/SP control-action rows, totaling {len(qualified_alarm_actions)} action rows."
 )

display(
    fi1000_30pct_passing_alarms[
        ['alarm_id', 'alarm_start', 'alarm_end', 'min_fi1000', 'max_fi1000', 'expected_samples']
    ].reset_index(drop=True)
 )

print('\nMost operated tags - OP actions')
display(op_most_operated_tags)

print('\nMost operated tags - SP actions')
display(sp_most_operated_tags)

FI_1000 30% expansion band: [8.313356, 8.703490]
122 alarms stay inside this band for the full alarm duration.
74 of those alarms have matched OP/SP control-action rows, totaling 995 action rows.

,alarm_id,alarm_start,alarm_end,min_fi1000,max_fi1000,expected_samples
0,116,2022-12-08 07:59:18.355,2022-12-08 08:06:23.353,8.328461,8.422258,7
1,171,2023-05-02 04:42:34.805,2023-05-02 04:49:03.810,8.547328,8.611371,7
2,172,2023-05-02 06:11:50.852,2023-05-02 06:18:34.852,8.482380,8.637196,7
3,176,2023-05-21 00:05:56.808,2023-05-21 00:11:22.804,8.567216,8.632663,6
4,178,2023-06-04 14:05:18.855,2023-06-04 14:15:02.406,8.333061,8.495438,10
...,...,...,...,...,...,...
117,517,2025-05-22 12:13:57.733,2025-05-22 12:15:25.990,8.621990,8.674137,2
118,528,2025-06-17 17:30:50.107,2025-06-17 17:31:59.223,8.540364,8.540364,1
119,531,2025-06-18 16:53:59.501,2025-06-18 16:54:47.382,8.336717,8.336717,1
120,532,2025-06-19 12:31:42.504,2025-06-19 12:32:23.198,8.397397,8.397397,1
121,535,2025-06-21 22:15:17.359,2025-06-21 22:16:18.517,8.642810,8.642810,1

Most operated tags - OP actions

,action_type,tag,action_count,unique_alarm_count,after,before,during
0,OP,03LIC_1071,294,11,92,52,150
1,OP,03PIC_1013,101,22,21,64,16
2,OP,03FIC_3435,101,16,29,61,11
3,OP,03HIC_1151,42,6,15,21,6
4,OP,03HIC_1141,37,3,15,12,10
5,OP,03HIC_1183,31,3,9,14,8
6,OP,03FIC_1085,27,1,0,27,0
7,OP,03FIC_3415,22,3,2,14,6
8,OP,03LIC_1094,20,1,20,0,0
9,OP,03XAX_1002,14,2,0,4,10
10,OP,03XAX_1001,12,2,0,2,10
11,OP,03GM_0153C,4,2,1,2,1
12,OP,03LIC_1034,4,1,0,4,0
13,OP,03HIC_3100,3,3,2,0,1
14,OP,03GM_0153B,2,2,1,1,0
15,OP,03GM_0121A,2,1,0,0,2
16,OP,03HIC_3132,2,1,0,2,0
17,OP,03LIC_1016,2,1,0,2,0
18,OP,03PIC_3131,2,1,0,0,2
19,OP,03TI_0018_MOS,2,1,0,2,0
20,OP,03TI_0019_MOS,2,1,0,2,0
21,OP,03LIC_1031,1,1,0,1,0

Most operated tags - SP actions

,action_type,tag,action_count,unique_alarm_count,after,before,during
0,SP,03LIC_1034,145,26,34,78,33
1,SP,03LIC_1071,57,14,37,3,17
2,SP,03TIC_1009,22,10,6,15,1
3,SP,03LIC_1085,20,8,7,8,5
4,SP,03LIC_1016,11,6,3,2,6
5,SP,03PIC_1068,5,2,4,0,1
6,SP,03LIC_3408,2,2,1,1,0
7,SP,03PIC_3131,2,1,0,0,2
8,SP,03LIC_1031,1,1,0,1,0
9,SP,03LIC_1097,1,1,1,0,0
10,SP,03LIC_3153,1,1,1,0,0
11,SP,03LIC_3178,1,1,1,0,0

In [10]:
# Alarms within the FI_1000 30% expansion band that have no matched OP/SP control actions
matched_op_sp_alarm_ids = set(qualified_alarm_actions['alarm_id'].unique())

fi1000_30pct_alarms_without_op_sp_actions = (
    fi1000_30pct_passing_alarms.loc[
        ~fi1000_30pct_passing_alarms['alarm_id'].isin(matched_op_sp_alarm_ids),
        ['alarm_id', 'alarm_start', 'alarm_end', 'min_fi1000', 'max_fi1000', 'expected_samples'],
    ]
    .sort_values('alarm_id')
    .reset_index(drop=True)
 )

print(
    f"{len(fi1000_30pct_alarms_without_op_sp_actions)} alarms inside the FI_1000 30% expansion band have no matched OP/SP control-action rows."
 )
display(fi1000_30pct_alarms_without_op_sp_actions)

48 alarms inside the FI_1000 30% expansion band have no matched OP/SP control-action rows.

,alarm_id,alarm_start,alarm_end,min_fi1000,max_fi1000,expected_samples
0,116,2022-12-08 07:59:18.355,2022-12-08 08:06:23.353,8.328461,8.422258,7
1,171,2023-05-02 04:42:34.805,2023-05-02 04:49:03.810,8.547328,8.611371,7
2,200,2023-08-09 13:26:54.004,2023-08-09 13:33:46.004,8.418064,8.496234,7
3,226,2024-01-05 11:01:11.952,2024-01-05 11:07:29.953,8.388277,8.490507,6
4,228,2024-01-05 17:21:03.352,2024-01-05 17:24:44.357,8.411674,8.461634,3
5,229,2024-01-05 22:36:21.307,2024-01-05 22:40:05.104,8.597386,8.665996,4
6,230,2024-01-06 02:17:57.203,2024-01-06 02:22:53.201,8.443940,8.458315,5
7,234,2024-01-06 11:01:40.353,2024-01-06 11:05:59.354,8.489911,8.518058,4
8,235,2024-01-06 17:59:45.404,2024-01-06 18:04:41.404,8.535021,8.583914,5
9,241,2024-01-07 04:02:09.352,2024-01-07 04:05:14.354,8.471346,8.509773,3
10,242,2024-01-07 18:26:20.106,2024-01-07 18:31:29.104,8.358730,8.495160,5
11,244,2024-01-09 06:16:26.303,2024-01-09 06:22:08.557,8.498920,8.597966,6
12,245,2024-01-10 18:56:12.053,2024-01-10 19:01:05.302,8.543817,8.598170,5
13,253,2024-01-21 08:09:47.602,2024-01-21 08:14:17.602,8.432138,8.523184,5
14,290,2024-04-18 22:28:26.855,2024-04-18 22:31:28.854,8.522134,8.565679,3
15,295,2024-04-23 11:01:18.704,2024-04-23 11:06:53.954,8.536010,8.638226,5
16,297,2024-04-24 05:56:13.054,2024-04-24 05:59:37.053,8.612716,8.698197,3
17,303,2024-05-01 22:03:14.752,2024-05-01 22:05:59.754,8.616375,8.691650,2
18,306,2024-05-06 22:36:16.503,2024-05-06 22:39:11.502,8.617238,8.699391,3
19,307,2024-05-07 14:24:02.503,2024-05-07 14:30:40.304,8.509695,8.537422,6
20,308,2024-05-07 17:04:59.854,2024-05-07 17:09:46.352,8.357193,8.397298,5
21,318,2024-05-10 02:35:03.253,2024-05-10 02:38:47.253,8.427602,8.459361,3
22,319,2024-05-10 06:43:00.703,2024-05-10 06:47:55.702,8.641406,8.670154,4
23,320,2024-05-11 00:21:56.154,2024-05-11 00:26:07.404,8.445528,8.579811,5
24,321,2024-05-11 02:58:33.205,2024-05-11 03:04:44.953,8.376862,8.608816,6
25,322,2024-05-11 13:46:52.253,2024-05-11 13:51:59.252,8.492859,8.659769,5
26,326,2024-05-12 02:15:26.554,2024-05-12 02:18:35.555,8.572324,8.601069,3
27,329,2024-05-17 12:39:04.003,2024-05-17 12:41:45.502,8.504373,8.570893,2
28,331,2024-05-21 06:14:16.153,2024-05-21 06:18:05.154,8.401290,8.525164,4
29,382,2024-06-29 11:20:05.154,2024-06-29 11:22:15.153,8.520190,8.579774,2
30,394,2024-07-18 16:30:27.252,2024-07-18 16:34:36.803,8.368390,8.466088,4
31,413,2024-08-27 04:52:43.652,2024-08-27 04:56:43.653,8.519086,8.591123,4
32,415,2024-08-29 07:18:29.452,2024-08-29 07:21:03.452,8.546250,8.586321,3
33,419,2024-09-12 00:52:14.105,2024-09-12 00:55:20.102,8.600732,8.648463,3
34,420,2024-09-12 12:24:18.253,2024-09-12 12:26:38.253,8.651174,8.675516,2
35,422,2024-09-16 04:33:58.804,2024-09-16 04:37:53.851,8.541741,8.574946,4
36,427,2024-09-21 05:21:35.354,2024-09-21 05:23:31.354,8.621848,8.655970,2
37,430,2024-09-22 00:43:50.101,2024-09-22 00:46:26.353,8.506560,8.604015,3
38,431,2024-09-24 03:51:25.054,2024-09-24 04:11:39.553,8.440629,8.645116,20
39,435,2024-10-06 03:17:12.555,2024-10-06 03:19:29.556,8.540176,8.548642,2
40,464,2024-12-26 15:13:02.889,2024-12-26 15:16:15.147,8.668840,8.696558,3
41,477,2025-01-09 03:42:12.514,2025-01-09 04:38:46.809,8.438030,8.651526,56
42,478,2025-01-09 07:12:33.384,2025-01-09 07:16:55.649,8.544545,8.611132,4
43,479,2025-01-09 08:17:52.639,2025-01-09 08:20:46.496,8.644894,8.687680,3
44,482,2025-01-14 06:35:00.639,2025-01-14 06:38:26.242,8.389374,8.419071,3
45,487,2025-01-16 11:07:26.293,2025-01-16 11:08:34.304,8.628880,8.628880,1
46,490,2025-04-19 17:22:41.581,2025-04-19 17:23:50.656,8.477488,8.477488,1
47,492,2025-04-20 07:29:40.425,2025-04-20 07:35:44.424,8.392848,8.540930,6

In [11]:
# Alarm IDs only: FI_1000 30% expansion band alarms without matched OP/SP control actions
no_op_sp_alarm_ids = fi1000_30pct_alarms_without_op_sp_actions['alarm_id'].tolist()
print(no_op_sp_alarm_ids)

[116, 171, 200, 226, 228, 229, 230, 234, 235, 241, 242, 244, 245, 253, 290, 295, 297, 303, 306, 307, 308, 318, 319, 320, 321, 322, 326, 329, 331, 382, 394, 413, 415, 419, 420, 422, 427, 430, 431, 435, 464, 477, 478, 479, 482, 487, 490, 492]