# Historian Events Loader

This notebook processes the historian and events data for a given alarm tag.

**Workflow:**
1. Load the alarm tag's related-tag information from the Excel workbook (`UC3_Alarm_Tags_Presentation_30MAY2026.xlsx`).
2. Extract DCS tag names and their associated asset IDs from the sheet.
3. Map those short asset IDs (e.g. `1E`, `1F`) to UUIDs using the `ADNOC-B.json` config file.
4. Discover which UUID folders exist under `Historian_Events/Historian/` and `Historian_Events/events/`.
5. Load the historian time-series parquet files for each related tag.
6. Load the event parquet files (_E, _EA, _EAL) for each asset.

**Target tag for this run:** `03TIC_1023` (sheet: `03TIC_1023 PVLO_PVHI`)

## 0. Configuration

In [1]:
# ── Paths ──────────────────────────────────────────────────────────────────────
import os

REPO_ROOT          = os.path.abspath(os.path.join(os.path.dirname(os.getcwd()), '.'))
DATA_DIR           = os.path.join(REPO_ROOT, 'DATA')
HISTORIAN_ROOT     = os.path.join(DATA_DIR, 'Historian_Events')
HISTORIAN_DIR      = os.path.join(HISTORIAN_ROOT, 'Historian')   # tag time-series
EVENTS_DIR         = os.path.join(HISTORIAN_ROOT, 'events')       # alarm/event tables
EXCEL_FILE         = os.path.join(DATA_DIR, 'UC3_Alarm_Tags_Presentation_30MAY2026.xlsx')
ADNOC_JSON         = os.path.join(DATA_DIR, 'config', 'config', 'EMDB', 'ADNOC-B.json')

# ── Target alarm tag ──────────────────────────────────────────────────────────
TARGET_TAG         = '03PIC_1104'
EXCEL_HEADER_ROW   = 6      # 0-indexed row that contains column headers

# ── Per-tag asset ID overrides ─────────────────────────────────────────────────
# If a tag's assets are known and should not be auto-derived from the Excel sheet,
# list them explicitly here. Keys are TARGET_TAG values.
ASSET_ID_OVERRIDE = {
    '03LIC_1071': ['1E', '1F', '1I', '1K', '1L'],
}

# Auto-detect the sheet whose name contains TARGET_TAG
import openpyxl
_wb = openpyxl.load_workbook(EXCEL_FILE, read_only=True, data_only=True)
_matches = [s for s in _wb.sheetnames if TARGET_TAG in s]
_wb.close()
if not _matches:
    raise ValueError(f"No sheet found containing '{TARGET_TAG}' in {EXCEL_FILE}")
SHEET_NAME = _matches[0]


print(f"REPO_ROOT      : {REPO_ROOT}")
print(f"SHEET_NAME     : {SHEET_NAME}  (auto-detected)")

print(f"EXCEL_FILE     : {EXCEL_FILE}")
print(f"TARGET_TAG     : {TARGET_TAG}")

print(f"ADNOC_JSON     : {ADNOC_JSON}")
print(f"EVENTS_DIR     : {EVENTS_DIR}")
print(f"HISTORIAN_DIR  : {HISTORIAN_DIR}")

REPO_ROOT      : /home/h604827/ControlActions
SHEET_NAME     : 03PIC_1104 PVHI  (auto-detected)
EXCEL_FILE     : /home/h604827/ControlActions/DATA/UC3_Alarm_Tags_Presentation_30MAY2026.xlsx
TARGET_TAG     : 03PIC_1104
ADNOC_JSON     : /home/h604827/ControlActions/DATA/config/config/EMDB/ADNOC-B.json
EVENTS_DIR     : /home/h604827/ControlActions/DATA/Historian_Events/events
HISTORIAN_DIR  : /home/h604827/ControlActions/DATA/Historian_Events/Historian

## 1. Imports

In [2]:
import json
import pandas as pd

print(f"pandas  : {pd.__version__}")

pandas  : 2.3.3

## 2. Load Related-Tag Information from Excel

Each sheet in the Excel workbook describes the related tags for one alarm.  
We extract **DCS Tag Name**, **DESCRIPTION**, **PARAMETER**, **IS DATA AVAILABLE?** and **ASSET ID**.

In [3]:
print(f"Reading sheet '{SHEET_NAME}' from:\n  {EXCEL_FILE}\n")

df_sheet = pd.read_excel(EXCEL_FILE, sheet_name=SHEET_NAME, header=EXCEL_HEADER_ROW)

print(f"Raw sheet shape  : {df_sheet.shape}")
print(f"Columns ({len(df_sheet.columns)}):")
for c in df_sheet.columns:
    print(f"  {c}")

Reading sheet '03PIC_1104 PVHI' from:
  /home/h604827/ControlActions/DATA/UC3_Alarm_Tags_Presentation_30MAY2026.xlsx

Raw sheet shape  : (55, 27)
Columns (27):
  Remarks
  Potential Input parameter
  Description
  Causes
  Plant
  P&ID
  SME Comments
  Unnamed: 7
  Unnamed: 8
  MH Comments
  DCS Tag Name
  DESCRIPTION
  PARAMETER
  IS DATA AVAILABLE?
  SP-HIGH LIMIT
  SP-LOW LIMIT
  EXTENDED PV HIGH LIMIT
  PV-HIGH LIMIT
  EXTENDED PV LOW LIMIT
  PV-LOW LIMIT
  OP-HIGH LIMIT
  OP-LOW LIMIT
  PHD_TAG AVILABLE
  FILE NAME
  ASSET ID
  AVAILABLE IN APC
  SAFETY MANAGER TAGS

In [4]:
# Keep only rows that have a DCS Tag Name
KEEP_COLS = ['Potential Input parameter', 'DCS Tag Name', 'DESCRIPTION', 'PARAMETER',
             'IS DATA AVAILABLE?', 'ASSET ID']

df_tags = (
    df_sheet[KEEP_COLS]
    .dropna(subset=['DCS Tag Name'])
    .copy()
)

# Normalise strings
df_tags['DCS Tag Name'] = df_tags['DCS Tag Name'].str.strip()
df_tags['ASSET ID']     = df_tags['ASSET ID'].astype(str).str.strip()

# Reset index for clean display
df_tags = df_tags.reset_index(drop=True)

print(f"Related tags found: {len(df_tags)}")
print()
display(df_tags)

Related tags found: 36

,Potential Input parameter,DCS Tag Name,DESCRIPTION,PARAMETER,IS DATA AVAILABLE?,ASSET ID
0,03TI_1408,03TI_1408,3E105 GAS TO 3E103 TEMP,PV,YES,1F
1,03SDV_3198,03SDV_3198,3C152 GAS BYPASS VALV,PV,YES,1K
2,03SDV_3197,03SDV_3197,3C152 GAS INLET SDV,PV,YES,1K
3,03PIC_1068,03PIC_1068,3C102 OVHD PRES,PV,YES,1F
4,03PIC_1104,03PIC_1104,3C105 OVHD GAS PRES,PV,YES,1F
5,03TI_1427,03TI_1427,3C105 OVHD GAS TEMP,PV,YES,1F
6,03TI_1099,03TI_1099,3C105 TRAY#11 TEMP,PV,YES,1F
7,03TI_1100,03TI_1100,3C105 TRAY# 7 TEMP,PV,YES,1F
8,03TI_1101,03TI_1101,3C105 TRAY# 3 TEMP,PV,YES,1F
9,03TI_1102,03TI_1102,3C105 TRAY#1 TEMP,PV,YES,1F
10,03PIC_3002,03PIC_3002,3K152 START UP PIC,PV,YES,1J
11,03PIC_3000,03PIC_3000,3K152 SUC PRES CTRL,PV,YES,1J
12,03TIC_3008,03TIC_3008,3K152 COMP SUC TEMP CCC,PV,YES,1J
13,03FIC_3000,03FIC_3000,3K152 COMP SUC FLW,PV,YES,1J
14,03PDI_3011,03PDI_3011,3K152 COMP SUC STRNR DP,PV,YES,1J
15,03PDI_3011,03PDI_3011,3K152 COMP SUC STRNR DP,PV,YES,1J
16,03TIC_3014,03TIC_3014,3K152 COMP DISCH TEMP,PV,YES,1J
17,03TI_3016,03TI_3016,3K152 CMP DIS TMP TR,PV,YES,1J
18,03PI_3017,03PI_3017,3K152 COMP DISCH PRES,PV,YES,1J
19,03LIC_3153,03LIC_3153,3C151 H/C LEVEL,PV,YES,1K
20,03LIC_3178,03LIC_3178,3C152 LEVEL,PV,YES,1K
21,03LIC_1071,03LIC_1071,3E107 LEVEL,PV,YES,1F
22,03PIC_3131,03PIC_3131,3C155 PRES,PV,YES,1I
23,03FIC_1085,03FIC_1085,3G112/A DISCH FLW,PV,YES,1F
24,03LIC_1094,03LIC_1094,3C105 CHIMNEY TRAY LVL,PV,YES,1F
25,03GM_0114_R,03GM_0114_R,3C105 REBOILER PUMP,PV,YES,1F
26,03GM_0114A_R,03GM_0114A_R,3C105 REBOILER PUMP-A,PV,YES,1F
27,03FIC_1141,03FI_1141A,3K101 1ST SUC FLW,PV,YES,1L
28,03FCV_3132,03HIC_3132,3K151 JT VALVE HIC,OP,YES,1H
29,03LIC_1097,03LIC_1097,3C105 BOTTOM LEVEL,PV,YES,1F
30,03FIC_1474,03FIC_1474,MLP TR-1 DISC FLW,PV,YES,3I
31,03FIC_3435,03FIC_3435,HYP-1 BYPASS FLW,PV,YES,1K
32,02FI_1000,02FI_1000,TRAIN 1 FEED,PV,YES,1A
33,03FI_1105,03FI_1105,3C105 OVHD GAS FLW,PV,YES,1F
34,03FI_3173,03FI_3173,3G151A/B DISCH FLW,PV,YES,1K
35,03FI_3188,03FI_3188,3G152A/B DISCH FLW,PV,YES,1K

## 3. Load ADNOC-B.json and Build Asset-ID → UUID Mapping

The JSON config contains one entry per asset node in the ADNOC Buhasa plant hierarchy.  
Leaf nodes whose `Name` matches the short asset ID in the sheet provide the UUID we need.

In [5]:
print(f"Reading asset config:\n  {ADNOC_JSON}\n")

with open(ADNOC_JSON, 'r') as f:
    asset_nodes = json.load(f)

print(f"Total nodes in ADNOC-B.json : {len(asset_nodes)}")

# Build a flat map:  short-name (e.g. '1E') → UUID
# We only care about leaf nodes under TRAIN_1 (adjust if other areas are needed)
asset_id_to_uuid = {}
for node in asset_nodes:
    asset_id_to_uuid[node['Name']] = {
        'uuid'      : node['Id'],
        'hierarchy' : node['Hierarchy'],
        'leaf'      : node['LeafNode'],
    }

print(f"Unique asset names mapped    : {len(asset_id_to_uuid)}")
print()

# Show all leaf nodes for easy inspection
leaf_map = pd.DataFrame(
    [{'Asset Name': k, 'UUID': v['uuid'], 'Hierarchy': v['hierarchy'], 'IsLeaf': v['leaf']}
     for k, v in asset_id_to_uuid.items()]
).sort_values('Asset Name').reset_index(drop=True)

print("Full asset map (all nodes):")
display(leaf_map)

Reading asset config:
  /home/h604827/ControlActions/DATA/config/config/EMDB/ADNOC-B.json

Total nodes in ADNOC-B.json : 74
Unique asset names mapped    : 74

Full asset map (all nodes):

,Asset Name,UUID,Hierarchy,IsLeaf
0,1A,8b999a4a-2a1e-4d6c-b76d-7a498fb5c4a3,ADNOC\BUHASA\ADNOC-B\TRAIN_1\1A,True
1,1B,f0c70dd0-139e-4102-b75d-77bccee3ca83,ADNOC\BUHASA\ADNOC-B\TRAIN_1\1B,True
2,1C,c71817e8-5df3-4ad6-89fb-0b71ec7d9f96,ADNOC\BUHASA\ADNOC-B\TRAIN_1\1C,True
3,1D,9cac06f4-131b-4af0-aea0-17b223973d12,ADNOC\BUHASA\ADNOC-B\TRAIN_1\1D,True
4,1E,072404dc-ae93-4239-9f6b-f4624391c391,ADNOC\BUHASA\ADNOC-B\TRAIN_1\1E,True
...,...,...,...,...
69,FIRE & GAS,de29a368-6e72-48a4-bbd2-84c32d2ac510,ADNOC\BUHASA\ADNOC-B\FIRE & GAS,False
70,LEAN_GAS,a663c56b-aafd-4a6a-837f-c8677655e9ca,ADNOC\BUHASA\ADNOC-B\LEAN_GAS,False
71,TRAIN_1,cdfe1dc7-d3db-4efe-a9b6-c5dec2902ccb,ADNOC\BUHASA\ADNOC-B\TRAIN_1,False
72,TRAIN_2,cc6268d1-0fe2-4fc2-8d84-79f6080b172d,ADNOC\BUHASA\ADNOC-B\TRAIN_2,False
73,UTILITES,fca4a64c-7fa4-4d14-8806-bc649241b8ca,ADNOC\BUHASA\ADNOC-B\UTILITES,False

## 4. Map Sheet Asset IDs → UUIDs

For every unique asset ID referenced in the sheet, look up the corresponding UUID.

In [6]:
if TARGET_TAG in ASSET_ID_OVERRIDE:
    unique_assets = ASSET_ID_OVERRIDE[TARGET_TAG]
    print(f"NOTE: Using hardcoded asset override for {TARGET_TAG}: {unique_assets}")
else:
    unique_assets = sorted(df_tags['ASSET ID'].dropna().unique())
print(f"Unique ASSET IDs in sheet : {unique_assets}")
print()

mapping_rows = []
for asset_name in unique_assets:
    if asset_name in asset_id_to_uuid:
        info = asset_id_to_uuid[asset_name]
        mapping_rows.append({
            'Asset Name' : asset_name,
            'UUID'       : info['uuid'],
            'Hierarchy'  : info['hierarchy'],
        })
        print(f"  {asset_name:6s}  →  {info['uuid']}  ({info['hierarchy']})")
    else:
        mapping_rows.append({'Asset Name': asset_name, 'UUID': None, 'Hierarchy': None})
        print(f"  {asset_name:6s}  →  [NOT FOUND in ADNOC-B.json]")

df_asset_map = pd.DataFrame(mapping_rows)
print(f"\nResolved: {df_asset_map['UUID'].notna().sum()} / {len(df_asset_map)} assets")

Unique ASSET IDs in sheet : ['1A', '1F', '1H', '1I', '1J', '1K', '1L', '3I']

  1A      →  8b999a4a-2a1e-4d6c-b76d-7a498fb5c4a3  (ADNOC\BUHASA\ADNOC-B\TRAIN_1\1A)
  1F      →  ccfff937-ff8c-4f84-a31c-a41f00fa0ff8  (ADNOC\BUHASA\ADNOC-B\TRAIN_1\1F)
  1H      →  f84c869c-4c09-4485-9cdd-35a994fc2350  (ADNOC\BUHASA\ADNOC-B\TRAIN_1\1H)
  1I      →  0b4d6b2d-7ed9-42ad-8ed6-6ee2bd33172c  (ADNOC\BUHASA\ADNOC-B\TRAIN_1\1I)
  1J      →  49fe1f01-8f3d-4383-9a36-0d77de120771  (ADNOC\BUHASA\ADNOC-B\TRAIN_1\1J)
  1K      →  6024200f-19c3-422a-a0e3-695a29031803  (ADNOC\BUHASA\ADNOC-B\TRAIN_1\1K)
  1L      →  65f25414-8750-4713-b7a5-d073ee37c3d5  (ADNOC\BUHASA\ADNOC-B\TRAIN_1\1L)
  3I      →  e0f2c384-4118-4662-99a4-4957e28ae60e  (ADNOC\BUHASA\ADNOC-B\TRAIN_2\3I)

Resolved: 8 / 8 assets

In [7]:
# Attach UUID back to each row in df_tags for convenience
df_tags = df_tags.merge(
    df_asset_map.rename(columns={'Asset Name': 'ASSET ID'})[['ASSET ID', 'UUID']],
    on='ASSET ID', how='left'
)

print("df_tags enriched with UUID column:")
display(df_tags[['DCS Tag Name', 'DESCRIPTION', 'ASSET ID', 'UUID']])

df_tags enriched with UUID column:

,DCS Tag Name,DESCRIPTION,ASSET ID,UUID
0,03TI_1408,3E105 GAS TO 3E103 TEMP,1F,ccfff937-ff8c-4f84-a31c-a41f00fa0ff8
1,03SDV_3198,3C152 GAS BYPASS VALV,1K,6024200f-19c3-422a-a0e3-695a29031803
2,03SDV_3197,3C152 GAS INLET SDV,1K,6024200f-19c3-422a-a0e3-695a29031803
3,03PIC_1068,3C102 OVHD PRES,1F,ccfff937-ff8c-4f84-a31c-a41f00fa0ff8
4,03PIC_1104,3C105 OVHD GAS PRES,1F,ccfff937-ff8c-4f84-a31c-a41f00fa0ff8
5,03TI_1427,3C105 OVHD GAS TEMP,1F,ccfff937-ff8c-4f84-a31c-a41f00fa0ff8
6,03TI_1099,3C105 TRAY#11 TEMP,1F,ccfff937-ff8c-4f84-a31c-a41f00fa0ff8
7,03TI_1100,3C105 TRAY# 7 TEMP,1F,ccfff937-ff8c-4f84-a31c-a41f00fa0ff8
8,03TI_1101,3C105 TRAY# 3 TEMP,1F,ccfff937-ff8c-4f84-a31c-a41f00fa0ff8
9,03TI_1102,3C105 TRAY#1 TEMP,1F,ccfff937-ff8c-4f84-a31c-a41f00fa0ff8
10,03PIC_3002,3K152 START UP PIC,1J,49fe1f01-8f3d-4383-9a36-0d77de120771
11,03PIC_3000,3K152 SUC PRES CTRL,1J,49fe1f01-8f3d-4383-9a36-0d77de120771
12,03TIC_3008,3K152 COMP SUC TEMP CCC,1J,49fe1f01-8f3d-4383-9a36-0d77de120771
13,03FIC_3000,3K152 COMP SUC FLW,1J,49fe1f01-8f3d-4383-9a36-0d77de120771
14,03PDI_3011,3K152 COMP SUC STRNR DP,1J,49fe1f01-8f3d-4383-9a36-0d77de120771
15,03PDI_3011,3K152 COMP SUC STRNR DP,1J,49fe1f01-8f3d-4383-9a36-0d77de120771
16,03TIC_3014,3K152 COMP DISCH TEMP,1J,49fe1f01-8f3d-4383-9a36-0d77de120771
17,03TI_3016,3K152 CMP DIS TMP TR,1J,49fe1f01-8f3d-4383-9a36-0d77de120771
18,03PI_3017,3K152 COMP DISCH PRES,1J,49fe1f01-8f3d-4383-9a36-0d77de120771
19,03LIC_3153,3C151 H/C LEVEL,1K,6024200f-19c3-422a-a0e3-695a29031803
20,03LIC_3178,3C152 LEVEL,1K,6024200f-19c3-422a-a0e3-695a29031803
21,03LIC_1071,3E107 LEVEL,1F,ccfff937-ff8c-4f84-a31c-a41f00fa0ff8
22,03PIC_3131,3C155 PRES,1I,0b4d6b2d-7ed9-42ad-8ed6-6ee2bd33172c
23,03FIC_1085,3G112/A DISCH FLW,1F,ccfff937-ff8c-4f84-a31c-a41f00fa0ff8
24,03LIC_1094,3C105 CHIMNEY TRAY LVL,1F,ccfff937-ff8c-4f84-a31c-a41f00fa0ff8
25,03GM_0114_R,3C105 REBOILER PUMP,1F,ccfff937-ff8c-4f84-a31c-a41f00fa0ff8
26,03GM_0114A_R,3C105 REBOILER PUMP-A,1F,ccfff937-ff8c-4f84-a31c-a41f00fa0ff8
27,03FI_1141A,3K101 1ST SUC FLW,1L,65f25414-8750-4713-b7a5-d073ee37c3d5
28,03HIC_3132,3K151 JT VALVE HIC,1H,f84c869c-4c09-4485-9cdd-35a994fc2350
29,03LIC_1097,3C105 BOTTOM LEVEL,1F,ccfff937-ff8c-4f84-a31c-a41f00fa0ff8
30,03FIC_1474,MLP TR-1 DISC FLW,3I,e0f2c384-4118-4662-99a4-4957e28ae60e
31,03FIC_3435,HYP-1 BYPASS FLW,1K,6024200f-19c3-422a-a0e3-695a29031803
32,02FI_1000,TRAIN 1 FEED,1A,8b999a4a-2a1e-4d6c-b76d-7a498fb5c4a3
33,03FI_1105,3C105 OVHD GAS FLW,1F,ccfff937-ff8c-4f84-a31c-a41f00fa0ff8
34,03FI_3173,3G151A/B DISCH FLW,1K,6024200f-19c3-422a-a0e3-695a29031803
35,03FI_3188,3G152A/B DISCH FLW,1K,6024200f-19c3-422a-a0e3-695a29031803

## 5. Discover Available Folders in Historian_Events

The `Historian/` sub-folder holds **tag-level time-series** parquet files (one file per tag per asset).  
The `events/` sub-folder holds **alarm & event** parquet files for each asset.

We check which asset UUID folders actually exist on disk.

In [8]:
historian_folders = set(os.listdir(HISTORIAN_DIR))
events_folders    = set(os.listdir(EVENTS_DIR))

print(f"Folders found in Historian/ : {len(historian_folders)}")
print(f"Folders found in events/    : {len(events_folders)}")
print()

availability = []
for _, row in df_asset_map.iterrows():
    uuid = row['UUID']
    in_hist   = uuid in historian_folders if uuid else False
    in_events = uuid in events_folders    if uuid else False
    availability.append({
        'Asset Name'      : row['Asset Name'],
        'UUID'            : uuid,
        'In Historian/'   : in_hist,
        'In events/'      : in_events,
    })
    status = []
    if in_hist:   status.append('Historian/')
    if in_events: status.append('events/')
    status_str = ', '.join(status) if status else 'MISSING in both'
    print(f"  {row['Asset Name']:6s}  {uuid}  →  {status_str}")

df_availability = pd.DataFrame(availability)
print()
display(df_availability)

Folders found in Historian/ : 13
Folders found in events/    : 70

  1A      8b999a4a-2a1e-4d6c-b76d-7a498fb5c4a3  →  Historian/, events/
  1F      ccfff937-ff8c-4f84-a31c-a41f00fa0ff8  →  Historian/, events/
  1H      f84c869c-4c09-4485-9cdd-35a994fc2350  →  Historian/, events/
  1I      0b4d6b2d-7ed9-42ad-8ed6-6ee2bd33172c  →  Historian/, events/
  1J      49fe1f01-8f3d-4383-9a36-0d77de120771  →  Historian/, events/
  1K      6024200f-19c3-422a-a0e3-695a29031803  →  Historian/, events/
  1L      65f25414-8750-4713-b7a5-d073ee37c3d5  →  Historian/, events/
  3I      e0f2c384-4118-4662-99a4-4957e28ae60e  →  Historian/, events/

  Asset Name                                  UUID  In Historian/  In events/
0         1A  8b999a4a-2a1e-4d6c-b76d-7a498fb5c4a3           True        True
1         1F  ccfff937-ff8c-4f84-a31c-a41f00fa0ff8           True        True
2         1H  f84c869c-4c09-4485-9cdd-35a994fc2350           True        True
3         1I  0b4d6b2d-7ed9-42ad-8ed6-6ee2bd33172c           True        True
4         1J  49fe1f01-8f3d-4383-9a36-0d77de120771           True        True
5         1K  6024200f-19c3-422a-a0e3-695a29031803           True        True
6         1L  65f25414-8750-4713-b7a5-d073ee37c3d5           True        True
7         3I  e0f2c384-4118-4662-99a4-4957e28ae60e           True        True

## 6. Load Historian Time-Series Data

For each asset that has a folder in `Historian/`, list the available tag files and load  
the ones corresponding to the tags referenced in the sheet.

Each parquet file in `Historian/<UUID>/` is named `<TAG>.<PARAMETER>` (e.g. `03TIC_1023.PV`).  
Columns: `startdatetime`, `enddatetime`, `timestamp`, `value`, `S`.

In [9]:
historian_data = {}   # key: 'TAG.PARAM'  →  value: DataFrame

for _, asset_row in df_asset_map.iterrows():
    uuid       = asset_row['UUID']
    asset_name = asset_row['Asset Name']

    if not uuid or uuid not in historian_folders:
        print(f"[SKIP] {asset_name} — no Historian folder")
        continue

    asset_hist_dir = os.path.join(HISTORIAN_DIR, uuid)
    available_files = os.listdir(asset_hist_dir)

    # Tags in the sheet that belong to this asset
    asset_tags = df_tags.loc[df_tags['UUID'] == uuid, 'DCS Tag Name'].tolist()

    print(f"\n── Asset {asset_name} ({uuid}) ──")
    print(f"   Files in Historian folder : {len(available_files)}")
    print(f"   Tags in sheet for asset   : {asset_tags}")

    for tag in asset_tags:
        param = df_tags.loc[df_tags['DCS Tag Name'] == tag, 'PARAMETER'].values
        param = param[0] if len(param) > 0 else 'PV'
        filename = f"{tag}.{param}"

        filepath = os.path.join(asset_hist_dir, filename)
        if os.path.exists(filepath):
            df_hist = pd.read_parquet(filepath)
            df_hist['timestamp'] = pd.to_datetime(df_hist['timestamp'])
            historian_data[filename] = df_hist
            print(f"   ✓ Loaded  {filename:30s}  →  shape {df_hist.shape}  "
                  f"| range: {df_hist['timestamp'].min()} … {df_hist['timestamp'].max()}")
        else:
            # Try scanning available files for a match
            matches = [f for f in available_files if f.startswith(tag + '.')]
            if matches:
                for m in matches:
                    df_hist = pd.read_parquet(os.path.join(asset_hist_dir, m))
                    df_hist['timestamp'] = pd.to_datetime(df_hist['timestamp'])
                    historian_data[m] = df_hist
                    print(f"   ✓ Loaded  {m:30s}  →  shape {df_hist.shape}  "
                          f"| range: {df_hist['timestamp'].min()} … {df_hist['timestamp'].max()}")
            else:
                print(f"   ✗ Not found: {filename}")

print(f"\n{'='*60}")
print(f"Total historian series loaded: {len(historian_data)}")

── Asset 1A (8b999a4a-2a1e-4d6c-b76d-7a498fb5c4a3) ──
   Files in Historian folder : 11
   Tags in sheet for asset   : ['02FI_1000']
   ✓ Loaded  02FI_1000.PV                    →  shape (2130628, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00

── Asset 1F (ccfff937-ff8c-4f84-a31c-a41f00fa0ff8) ──
   Files in Historian folder : 50
   Tags in sheet for asset   : ['03TI_1408', '03PIC_1068', '03PIC_1104', '03TI_1427', '03TI_1099', '03TI_1100', '03TI_1101', '03TI_1102', '03LIC_1071', '03FIC_1085', '03LIC_1094', '03GM_0114_R', '03GM_0114A_R', '03LIC_1097', '03FI_1105']
   ✓ Loaded  03TI_1408.PV                    →  shape (2169302, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03PIC_1068.PV                   →  shape (2169275, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03PIC_1104.PV                   →  shape (2169275, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03TI_1427.PV                    →  shape (2169291, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03TI_1099.PV                    →  shape (2169306, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03TI_1100.PV                    →  shape (2169306, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03TI_1101.PV                    →  shape (2169306, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03TI_1102.PV                    →  shape (2169305, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03LIC_1071.PV                   →  shape (2168639, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03FIC_1085.PV                   →  shape (2144381, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03LIC_1094.PV                   →  shape (2169306, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✗ Not found: 03GM_0114_R.PV
   ✗ Not found: 03GM_0114A_R.PV
   ✓ Loaded  03LIC_1097.PV                   →  shape (2169291, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03FI_1105.PV                    →  shape (2169275, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00

── Asset 1H (f84c869c-4c09-4485-9cdd-35a994fc2350) ──
   Files in Historian folder : 15
   Tags in sheet for asset   : ['03HIC_3132']
   ✗ Not found: 03HIC_3132.OP

── Asset 1I (0b4d6b2d-7ed9-42ad-8ed6-6ee2bd33172c) ──
   Files in Historian folder : 25
   Tags in sheet for asset   : ['03PIC_3131']
   ✓ Loaded  03PIC_3131.PV                   →  shape (2134282, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00

── Asset 1J (49fe1f01-8f3d-4383-9a36-0d77de120771) ──
   Files in Historian folder : 31
   Tags in sheet for asset   : ['03PIC_3002', '03PIC_3000', '03TIC_3008', '03FIC_3000', '03PDI_3011', '03PDI_3011', '03TIC_3014', '03TI_3016', '03PI_3017']
   ✓ Loaded  03PIC_3002.PV                   →  shape (2134282, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03PIC_3000.PV                   →  shape (2134281, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03TIC_3008.PV                   →  shape (2134293, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03FIC_3000.PV                   →  shape (2134275, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03PDI_3011.PV                   →  shape (2134281, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03PDI_3011.PV                   →  shape (2134281, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03TIC_3014.PV                   →  shape (2134294, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03TI_3016.PV                    →  shape (2133839, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03PI_3017.PV                    →  shape (2134282, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00

── Asset 1K (6024200f-19c3-422a-a0e3-695a29031803) ──
   Files in Historian folder : 38
   Tags in sheet for asset   : ['03SDV_3198', '03SDV_3197', '03LIC_3153', '03LIC_3178', '03FIC_3435', '03FI_3173', '03FI_3188']
   ✗ Not found: 03SDV_3198.PV
   ✗ Not found: 03SDV_3197.PV
   ✓ Loaded  03LIC_3153.PV                   →  shape (2169301, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03LIC_3178.PV                   →  shape (2091336, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03FIC_3435.PV                   →  shape (2167054, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03FI_3173.PV                    →  shape (2169274, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00
   ✓ Loaded  03FI_3188.PV                    →  shape (2169274, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00

── Asset 1L (65f25414-8750-4713-b7a5-d073ee37c3d5) ──
   Files in Historian folder : 46
   Tags in sheet for asset   : ['03FI_1141A']
   ✓ Loaded  03FI_1141A.PV                   →  shape (2096863, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00

── Asset 3I (e0f2c384-4118-4662-99a4-4957e28ae60e) ──
   Files in Historian folder : 56
   Tags in sheet for asset   : ['03FIC_1474']
   ✓ Loaded  03FIC_1474.PV                   →  shape (2108675, 5)  | range: 2022-01-04 01:00:00 … 2026-01-10 01:00:00

============================================================
Total historian series loaded: 30

### 6a. Historian Data — Preview

In [10]:
for key, df_h in historian_data.items():
    print(f"\n── {key} ──")
    print(f"   Shape   : {df_h.shape}")
    print(f"   Columns : {df_h.columns.tolist()}")
    print(f"   Null %  : {(df_h['value'].isna().mean()*100):.2f}%  missing values")
    display(df_h.head(3))

── 02FI_1000.PV ──
   Shape   : (2130628, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 98.36%  missing values

         startdatetime          enddatetime           timestamp     value    S
0  2022-01-04 00:00:00  2022-01-04 01:00:00 2022-01-04 01:00:00  6.623204  NaN
1  2022-01-04 01:00:00  2022-01-04 02:00:00 2022-01-04 02:00:00  6.683493  NaN
2  2022-01-04 02:00:00  2022-01-04 03:00:00 2022-01-04 03:00:00  6.603747  NaN

── 03TI_1408.PV ──
   Shape   : (2169302, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 96.77%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,15.125644,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,15.075137,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,15.022305,NaN

── 03PIC_1068.PV ──
   Shape   : (2169275, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 96.77%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,24.788550,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,24.739596,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,24.602739,NaN

── 03PIC_1104.PV ──
   Shape   : (2169275, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 96.77%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,25.879502,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,25.886069,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,25.664119,NaN

── 03TI_1427.PV ──
   Shape   : (2169291, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 96.77%  missing values

         startdatetime          enddatetime           timestamp     value    S
0  2022-01-04 00:00:00  2022-01-04 01:00:00 2022-01-04 01:00:00  2.985161  NaN
1  2022-01-04 01:00:00  2022-01-04 02:00:00 2022-01-04 02:00:00  2.864699  NaN
2  2022-01-04 02:00:00  2022-01-04 03:00:00 2022-01-04 03:00:00  2.883098  NaN

── 03TI_1099.PV ──
   Shape   : (2169306, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 96.77%  missing values

         startdatetime          enddatetime           timestamp     value    S
0  2022-01-04 00:00:00  2022-01-04 01:00:00 2022-01-04 01:00:00  2.561075  NaN
1  2022-01-04 01:00:00  2022-01-04 02:00:00 2022-01-04 02:00:00  2.442290  NaN
2  2022-01-04 02:00:00  2022-01-04 03:00:00 2022-01-04 03:00:00  2.462104  NaN

── 03TI_1100.PV ──
   Shape   : (2169306, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 96.77%  missing values

         startdatetime          enddatetime           timestamp     value    S
0  2022-01-04 00:00:00  2022-01-04 01:00:00 2022-01-04 01:00:00  3.316353  NaN
1  2022-01-04 01:00:00  2022-01-04 02:00:00 2022-01-04 02:00:00  3.190857  NaN
2  2022-01-04 02:00:00  2022-01-04 03:00:00 2022-01-04 03:00:00  3.191172  NaN

── 03TI_1101.PV ──
   Shape   : (2169306, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 96.77%  missing values

         startdatetime          enddatetime           timestamp     value    S
0  2022-01-04 00:00:00  2022-01-04 01:00:00 2022-01-04 01:00:00  8.418470  NaN
1  2022-01-04 01:00:00  2022-01-04 02:00:00 2022-01-04 02:00:00  9.131096  NaN
2  2022-01-04 02:00:00  2022-01-04 03:00:00 2022-01-04 03:00:00  8.623444  NaN

── 03TI_1102.PV ──
   Shape   : (2169305, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 96.77%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,10.417978,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,11.354475,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,10.685127,NaN

── 03LIC_1071.PV ──
   Shape   : (2168639, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 96.77%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,36.391532,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,34.907829,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,36.295983,NaN

── 03FIC_1085.PV ──
   Shape   : (2144381, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 96.76%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,225.331936,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,227.730181,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,220.806756,NaN

── 03LIC_1094.PV ──
   Shape   : (2169306, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 96.77%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,56.255510,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,56.031961,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,55.866452,NaN

── 03LIC_1097.PV ──
   Shape   : (2169291, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 96.77%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,55.048610,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,55.032344,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,54.923939,NaN

── 03FI_1105.PV ──
   Shape   : (2169275, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 96.77%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,29177.693556,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,30238.885133,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,28867.080567,NaN

── 03PIC_3131.PV ──
   Shape   : (2134282, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 98.36%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,24.275822,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,24.217179,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,24.084796,NaN

── 03PIC_3002.PV ──
   Shape   : (2134282, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 98.36%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,11.780750,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,11.821516,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,11.752078,NaN

── 03PIC_3000.PV ──
   Shape   : (2134281, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 98.36%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,11.713813,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,11.754182,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,11.684823,NaN

── 03TIC_3008.PV ──
   Shape   : (2134293, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 98.36%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,26.178822,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,25.858365,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,25.902321,NaN

── 03FIC_3000.PV ──
   Shape   : (2134275, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 98.36%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,194155.731333,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,195184.366667,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,194730.231000,NaN

── 03PDI_3011.PV ──
   Shape   : (2134281, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 98.36%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,10.709313,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,10.819154,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,10.816950,NaN

── 03TIC_3014.PV ──
   Shape   : (2134294, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 98.36%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,80.628412,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,80.172164,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,80.277781,NaN

── 03TI_3016.PV ──
   Shape   : (2133839, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 98.36%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,80.708378,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,80.217470,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,80.274700,NaN

── 03PI_3017.PV ──
   Shape   : (2134282, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 98.36%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,21.698785,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,21.754865,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,21.630928,NaN

── 03LIC_3153.PV ──
   Shape   : (2169301, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 96.77%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,65.381254,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,64.749758,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,65.228069,NaN

── 03LIC_3178.PV ──
   Shape   : (2091336, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 96.77%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,46.119583,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,45.964821,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,45.976169,NaN

── 03FIC_3435.PV ──
   Shape   : (2167054, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 96.77%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,16597.419644,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,19800.213817,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,16961.888850,NaN

── 03FI_3173.PV ──
   Shape   : (2169274, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 96.77%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,26.015541,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,25.127526,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,25.117343,NaN

── 03FI_3188.PV ──
   Shape   : (2169274, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 96.77%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,26.140095,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,26.329515,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,26.600484,NaN

── 03FI_1141A.PV ──
   Shape   : (2096863, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 98.35%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,64246.638467,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,64965.659267,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,64371.866200,NaN

── 03FIC_1474.PV ──
   Shape   : (2108675, 5)
   Columns : ['startdatetime', 'enddatetime', 'timestamp', 'value', 'S']
   Null %  : 98.36%  missing values

,startdatetime,enddatetime,timestamp,value,S
0,2022-01-04 00:00:00,2022-01-04 01:00:00,2022-01-04 01:00:00,232.780198,NaN
1,2022-01-04 01:00:00,2022-01-04 02:00:00,2022-01-04 02:00:00,233.813448,NaN
2,2022-01-04 02:00:00,2022-01-04 03:00:00,2022-01-04 03:00:00,230.480291,NaN

## 7. Load Events Data

For each asset UUID folder in `events/`, there are up to three types of parquet files:

| Suffix | Content |
|--------|---------|
| `_E`   | Process/operator change events |
| `_EA`  | Alarm events (no last/next linkage) |
| `_EAL` | Alarm events **with** linked previous/next alarm (includes duration) |

We load all three types for every relevant asset.

In [11]:
events_data = {}   # key: '<asset_name>_<type>'  →  value: DataFrame

for _, asset_row in df_asset_map.iterrows():
    uuid       = asset_row['UUID']
    asset_name = asset_row['Asset Name']

    if not uuid or uuid not in events_folders:
        print(f"[SKIP] {asset_name} — no events folder")
        continue

    asset_events_dir = os.path.join(EVENTS_DIR, uuid)
    available_files  = os.listdir(asset_events_dir)

    print(f"\n── Asset {asset_name} ({uuid}) ──")
    print(f"   Files in events folder : {available_files}")

    for suffix, label in [('_E.parquet', 'ChangeEvents'), ('_EA.parquet', 'AlarmEvents'), ('_EAL.parquet', 'AlarmEventsLinked')]:
        match = [f for f in available_files if f.endswith(suffix)]
        if match:
            fp = os.path.join(asset_events_dir, match[0])
            df_ev = pd.read_parquet(fp)
            # Parse timestamp column where available — use format='mixed' to handle
            # rows where milliseconds are present/absent in the same column
            for ts_col in ['VT_Start', 'Time', 'timestamp']:
                if ts_col in df_ev.columns:
                    df_ev[ts_col] = pd.to_datetime(df_ev[ts_col], format='mixed')
            key = f"{asset_name}_{label}"
            events_data[key] = df_ev
            print(f"   ✓ Loaded  {match[0]:50s}  →  shape {df_ev.shape}")
        else:
            print(f"   ✗ No {suffix} file found")

print(f"\n{'='*60}")
print(f"Total event tables loaded: {len(events_data)}")

── Asset 1A (8b999a4a-2a1e-4d6c-b76d-7a498fb5c4a3) ──
   Files in events folder : ['8b999a4a-2a1e-4d6c-b76d-7a498fb5c4a3.parquet', '2021011814_2026011001_EAE.parquet', '2021011814_2026011001_EA.parquet', '2021011814_2026011001_EALE.parquet', '2021011814_2026011001_EAL.parquet', '2021011814_2026011001_E.parquet']

   ✓ Loaded  2021011814_2026011001_E.parquet                     →  shape (2507555, 30)
   ✓ Loaded  2021011814_2026011001_EA.parquet                    →  shape (54844, 24)
   ✓ Loaded  2021011814_2026011001_EAL.parquet                   →  shape (201117, 29)

── Asset 1F (ccfff937-ff8c-4f84-a31c-a41f00fa0ff8) ──
   Files in events folder : ['ccfff937-ff8c-4f84-a31c-a41f00fa0ff8.parquet', '2021011814_2026011001_EAE.parquet', '2021011814_2026011001_EA.parquet', '2021011814_2026011001_EALE.parquet', '2021011814_2026011001_EAL.parquet', '2021011814_2026011001_E.parquet']
   ✓ Loaded  2021011814_2026011001_E.parquet                     →  shape (138249, 30)
   ✓ Loaded  2021011814_2026011001_EA.parquet                    →  shape (44033, 24)
   ✓ Loaded  2021011814_2026011001_EAL.parquet                   →  shape (19238, 29)

── Asset 1H (f84c869c-4c09-4485-9cdd-35a994fc2350) ──
   Files in events folder : ['2021011814_2026011001_EAE.parquet', 'f84c869c-4c09-4485-9cdd-35a994fc2350.parquet', '2021011814_2026011001_EA.parquet', '2021011814_2026011001_EALE.parquet', '2021011814_2026011001_EAL.parquet', '2021011814_2026011001_E.parquet']
   ✓ Loaded  2021011814_2026011001_E.parquet                     →  shape (277370, 30)
   ✓ Loaded  2021011814_2026011001_EA.parquet                    →  shape (83813, 24)
   ✓ Loaded  2021011814_2026011001_EAL.parquet                   →  shape (32728, 29)

── Asset 1I (0b4d6b2d-7ed9-42ad-8ed6-6ee2bd33172c) ──
   Files in events folder : ['2021011814_2026011001_EAE.parquet', '0b4d6b2d-7ed9-42ad-8ed6-6ee2bd33172c.parquet', '2021011814_2026011001_EA.parquet', '2021011814_2026011001_EALE.parquet', '2021011814_2026011001_EAL.parquet', '2021011814_2026011001_E.parquet']
   ✓ Loaded  2021011814_2026011001_E.parquet                     →  shape (91578, 30)
   ✓ Loaded  2021011814_2026011001_EA.parquet                    →  shape (54842, 24)
   ✓ Loaded  2021011814_2026011001_EAL.parquet                   →  shape (5129, 29)

── Asset 1J (49fe1f01-8f3d-4383-9a36-0d77de120771) ──
   Files in events folder : ['2021011814_2026011001_EAE.parquet', '2021011814_2026011001_EA.parquet', '2021011814_2026011001_EALE.parquet', '2021011814_2026011001_EAL.parquet', '49fe1f01-8f3d-4383-9a36-0d77de120771.parquet', '2021011814_2026011001_E.parquet']
   ✓ Loaded  2021011814_2026011001_E.parquet                     →  shape (90779, 30)
   ✓ Loaded  2021011814_2026011001_EA.parquet                    →  shape (46413, 24)
   ✓ Loaded  2021011814_2026011001_EAL.parquet                   →  shape (3720, 29)

── Asset 1K (6024200f-19c3-422a-a0e3-695a29031803) ──
   Files in events folder : ['2021011814_2026011001_EAE.parquet', '6024200f-19c3-422a-a0e3-695a29031803.parquet', '2021011814_2026011001_EA.parquet', '2021011814_2026011001_EALE.parquet', '2021011814_2026011001_EAL.parquet', '2021011814_2026011001_E.parquet']
   ✓ Loaded  2021011814_2026011001_E.parquet                     →  shape (523768, 30)
   ✓ Loaded  2021011814_2026011001_EA.parquet                    →  shape (82657, 24)
   ✓ Loaded  2021011814_2026011001_EAL.parquet                   →  shape (19819, 29)

── Asset 1L (65f25414-8750-4713-b7a5-d073ee37c3d5) ──
   Files in events folder : ['2021011814_2026011001_EAE.parquet', '2021011814_2026011001_EA.parquet', '2021011814_2026011001_EALE.parquet', '65f25414-8750-4713-b7a5-d073ee37c3d5.parquet', '2021011814_2026011001_EAL.parquet', '2021011814_2026011001_E.parquet']
   ✓ Loaded  2021011814_2026011001_E.parquet                     →  shape (1051748, 30)
   ✓ Loaded  2021011814_2026011001_EA.parquet                    →  shape (86427, 24)
   ✓ Loaded  2021011814_2026011001_EAL.parquet                   →  shape (49369, 29)

── Asset 3I (e0f2c384-4118-4662-99a4-4957e28ae60e) ──
   Files in events folder : ['e0f2c384-4118-4662-99a4-4957e28ae60e.parquet', '2021011814_2026011001_EAE.parquet', '2021011814_2026011001_EA.parquet', '2021011814_2026011001_EALE.parquet', '2021011814_2026011001_EAL.parquet', '2021011814_2026011001_E.parquet']
   ✓ Loaded  2021011814_2026011001_E.parquet                     →  shape (388599, 30)
   ✓ Loaded  2021011814_2026011001_EA.parquet                    →  shape (56023, 24)
   ✓ Loaded  2021011814_2026011001_EAL.parquet                   →  shape (16142, 29)

============================================================
Total event tables loaded: 24

### 7a. Events Data — Preview

In [12]:
for key, df_ev in events_data.items():
    print(f"\n── {key} ──")
    print(f"   Shape   : {df_ev.shape}")
    print(f"   Columns : {df_ev.columns.tolist()}")
    display(df_ev.head(3))

── 1A_ChangeEvents ──
   Shape   : (2507555, 30)
   Columns : ['Action', 'Actor', 'AreaName', 'AlarmLimit', 'Block', 'Category', 'ConditionName', 'Description', 'EventID', 'Flags', 'LocalTime', 'LocationFullName', 'LocationTagName', 'PrevValue', 'Priority', 'ReceivedDelay', 'ServerName', 'ShelvedReason', 'Source', 'SourceParameter', 'Station', 'Time', 'TransactionID', 'Units', 'Value', 'VT_Start', 'H', 'TagID', 'AlarmStatus', 'S']

,Action,Actor,AreaName,AlarmLimit,Block,Category,ConditionName,Description,EventID,Flags,...,Station,Time,TransactionID,Units,Value,VT_Start,H,TagID,AlarmStatus,S
0,None,None,1A,NaN,None,14,None,PROCESS EVNT RCVRY 1A ...,31214430,NaN,...,None,1974-03-17 20:27:01.115608,31214430,None,None,2021-10-11 10:31:51.560800,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01
1,None,None,1A,NaN,None,14,None,PROCESS EVNT RCVRY 1A ...,31214424,NaN,...,None,1974-03-17 20:27:01.116026,31214424,None,None,2021-10-11 10:31:51.602600,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01
2,None,None,1A,NaN,None,14,None,PROCESS EVNT RCVRY 1A ...,31214423,NaN,...,None,1974-03-17 20:27:01.116028,31214423,None,None,2021-10-11 10:31:51.602800,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01

── 1A_AlarmEvents ──
   Shape   : (54844, 24)
   Columns : ['ServerName', 'EventID', 'IntervalIdentifier', 'Priority', 'Parameter', 'FromValue', 'ToValue', 'Value', 'Description', 'ACTION', 'Unit', 'UnitOfMeasure', 'TagName', 'Area', 'Limit', 'LocationFullName', 'LocationTagName', 'AlarmStatus', 'VT_Start', 'TagID', 'EventTypeID', 'VT_End', 'H', 'S']

,ServerName,EventID,IntervalIdentifier,Priority,Parameter,FromValue,ToValue,Value,Description,ACTION,...,Limit,LocationFullName,LocationTagName,AlarmStatus,VT_Start,TagID,EventTypeID,VT_End,H,S
0,S1-PROD-ESVT01,61059050,CHANGE,16,None,None,INACTIVE,INACTIVE,PTEXECST,None,...,NaN,/Assets/TRAIN_1/1A,1A,None,2023-05-04 13:21:48.203000,$DET0108,4,None,2023_05_04_13,S1-PROD-ESVT01
1,S1-PROD-ESVT01,61059051,None,16,None,None,None,None,PTEXECST ACTIVE INACTIVE,None,...,NaN,/Assets/TRAIN_1/1A,1A,None,2023-05-04 13:21:48.203000,$DET0108,4,None,2023_05_04_13,S1-PROD-ESVT01
2,S1-PROD-ESVT01,61059053,CHANGE,16,None,None,INACTIVE,INACTIVE,PTEXECST,None,...,NaN,/Assets/TRAIN_1/1A,1A,None,2023-05-04 13:21:55.256300,$DET0108,4,None,2023_05_04_13,S1-PROD-ESVT01

── 1A_AlarmEventsLinked ──
   Shape   : (201117, 29)
   Columns : ['ServerName', 'EventID', 'IntervalIdentifier', 'Priority', 'Parameter', 'FromValue', 'ToValue', 'Value', 'Description', 'ACTION', 'Unit', 'UnitOfMeasure', 'TagName', 'Area', 'Limit', 'LocationFullName', 'LocationTagName', 'AlarmStatus', 'VT_Start', 'TagID', 'EventTypeID', 'VT_End', 'LastEvent', 'NextEvent', 'rowid', 'Seconds', 'PrevSeconds', 'H', 'S']

,ServerName,EventID,IntervalIdentifier,Priority,Parameter,FromValue,ToValue,Value,Description,ACTION,...,TagID,EventTypeID,VT_End,LastEvent,NextEvent,rowid,Seconds,PrevSeconds,H,S
0,S1-PROD-ESVT01,39184708,CMDDIS,16,None,None,MOVING,MOVING,2K101 ESD VENT VALV,None,...,02EDPV_1052,1,None,0,2,1,11496,6,2022_03_24_15,S1-PROD-ESVT01
1,S1-PROD-ESVT01,39250191,CMDDIS,16,None,None,OPEN,OPEN,2K101 ESD VENT VALV,OK,...,02EDPV_1052,2,None,1,1,2,599,11496,2022_03_24_18,S1-PROD-ESVT01
2,S1-PROD-ESVT01,39255892,CMDDIS,16,None,None,MOVING,MOVING,2K101 ESD VENT VALV,None,...,02EDPV_1052,1,None,2,2,3,1876,599,2022_03_24_18,S1-PROD-ESVT01

── 1F_ChangeEvents ──
   Shape   : (138249, 30)
   Columns : ['Action', 'Actor', 'AreaName', 'AlarmLimit', 'Block', 'Category', 'ConditionName', 'Description', 'EventID', 'Flags', 'LocalTime', 'LocationFullName', 'LocationTagName', 'PrevValue', 'Priority', 'ReceivedDelay', 'ServerName', 'ShelvedReason', 'Source', 'SourceParameter', 'Station', 'Time', 'TransactionID', 'Units', 'Value', 'VT_Start', 'H', 'TagID', 'AlarmStatus', 'S']

,Action,Actor,AreaName,AlarmLimit,Block,Category,ConditionName,Description,EventID,Flags,...,Station,Time,TransactionID,Units,Value,VT_Start,H,TagID,AlarmStatus,S
0,None,None,1F,NaN,None,14,None,PROCESS EVNT RCVRY 1F ...,31214526,NaN,...,None,1974-03-17 20:27:01.540022,31214526,None,None,2021-10-11 10:32:34.002200,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01
1,None,None,1F,NaN,None,14,None,PROCESS EVNT RCVRY 1F ...,31214527,NaN,...,None,1974-03-17 20:27:01.540081,31214527,None,None,2021-10-11 10:32:34.008100,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01
2,None,None,1F,NaN,None,14,None,PROCESS EVNT RCVRY 1F ...,31596740,NaN,...,None,1974-03-18 00:47:10.061527,31596740,None,None,2021-10-29 12:06:46.152700,2021_10_29_12,$CONSOLE01,None,S1-PROD-ESVT01

── 1F_AlarmEvents ──
   Shape   : (44033, 24)
   Columns : ['ServerName', 'EventID', 'IntervalIdentifier', 'Priority', 'Parameter', 'FromValue', 'ToValue', 'Value', 'Description', 'ACTION', 'Unit', 'UnitOfMeasure', 'TagName', 'Area', 'Limit', 'LocationFullName', 'LocationTagName', 'AlarmStatus', 'VT_Start', 'TagID', 'EventTypeID', 'VT_End', 'H', 'S']

,ServerName,EventID,IntervalIdentifier,Priority,Parameter,FromValue,ToValue,Value,Description,ACTION,...,Limit,LocationFullName,LocationTagName,AlarmStatus,VT_Start,TagID,EventTypeID,VT_End,H,S
0,S1-PROD-ESVT01,46281730,MESSAGE,16,None,None,None,None,20May22 17:31:07 * Completed AM Schedule Data ...,ACK,...,NaN,/Assets/TRAIN_1/1F,1F,None,2022-05-20 19:01:26.246500,$Prsts30,4,None,2022_05_20_19,S1-PROD-ESVT01
1,S1-PROD-ESVT01,31214528,None,16,None,None,None,None,UT ALM RECOV ...,None,...,NaN,/Assets/TRAIN_1/1F,1F,None,2021-10-11 10:32:34.007500,$UNITOPS,4,None,2021_10_11_10,S1-PROD-ESVT01
2,S1-PROD-ESVT01,31214529,None,16,None,None,None,None,UT RECOV CMP ...,None,...,NaN,/Assets/TRAIN_1/1F,1F,None,2021-10-11 10:32:34.007500,$UNITOPS,4,None,2021_10_11_10,S1-PROD-ESVT01

── 1F_AlarmEventsLinked ──
   Shape   : (19238, 29)
   Columns : ['ServerName', 'EventID', 'IntervalIdentifier', 'Priority', 'Parameter', 'FromValue', 'ToValue', 'Value', 'Description', 'ACTION', 'Unit', 'UnitOfMeasure', 'TagName', 'Area', 'Limit', 'LocationFullName', 'LocationTagName', 'AlarmStatus', 'VT_Start', 'TagID', 'EventTypeID', 'VT_End', 'LastEvent', 'NextEvent', 'rowid', 'Seconds', 'PrevSeconds', 'H', 'S']

,ServerName,EventID,IntervalIdentifier,Priority,Parameter,FromValue,ToValue,Value,Description,ACTION,...,TagID,EventTypeID,VT_End,LastEvent,NextEvent,rowid,Seconds,PrevSeconds,H,S
0,S1-PROD-ESVT01,31974016,OFFNORM,16,None,None,MOVING,MOVING,3E106 SHELL INLET VALVE,None,...,03EDPV_1075,1,None,0,2,3,602,6,2021_11_25_09,S1-PROD-ESVT01
1,S1-PROD-ESVT01,31974244,OFFNORM,16,None,None,CLOSE,CLOSE,3E106 SHELL INLET VALVE,OK,...,03EDPV_1075,2,None,1,1,4,727,602,2021_11_25_09,S1-PROD-ESVT01
2,S1-PROD-ESVT01,31974604,OFFNORM,16,None,None,MOVING,MOVING,3E106 SHELL INLET VALVE,None,...,03EDPV_1075,1,None,2,2,5,438,727,2021_11_25_09,S1-PROD-ESVT01

── 1H_ChangeEvents ──
   Shape   : (277370, 30)
   Columns : ['Action', 'Actor', 'AreaName', 'AlarmLimit', 'Block', 'Category', 'ConditionName', 'Description', 'EventID', 'Flags', 'LocalTime', 'LocationFullName', 'LocationTagName', 'PrevValue', 'Priority', 'ReceivedDelay', 'ServerName', 'ShelvedReason', 'Source', 'SourceParameter', 'Station', 'Time', 'TransactionID', 'Units', 'Value', 'VT_Start', 'H', 'TagID', 'AlarmStatus', 'S']

,Action,Actor,AreaName,AlarmLimit,Block,Category,ConditionName,Description,EventID,Flags,...,Station,Time,TransactionID,Units,Value,VT_Start,H,TagID,AlarmStatus,S
0,None,None,1H,NaN,None,14,None,PROCESS EVNT RCVRY 1H ...,31214550,NaN,...,None,1974-03-17 20:27:01.708976,31214550,None,None,2021-10-11 10:32:50.897600,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01
1,None,None,1H,NaN,None,14,None,PROCESS EVNT RCVRY 1H ...,31214552,NaN,...,None,1974-03-17 20:27:01.709048,31214552,None,None,2021-10-11 10:32:50.904800,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01
2,None,None,1H,NaN,None,14,None,PROCESS EVNT RCVRY 1H ...,31214551,NaN,...,None,1974-03-17 20:27:01.710228,31214551,None,None,2021-10-11 10:32:51.022800,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01

── 1H_AlarmEvents ──
   Shape   : (83813, 24)
   Columns : ['ServerName', 'EventID', 'IntervalIdentifier', 'Priority', 'Parameter', 'FromValue', 'ToValue', 'Value', 'Description', 'ACTION', 'Unit', 'UnitOfMeasure', 'TagName', 'Area', 'Limit', 'LocationFullName', 'LocationTagName', 'AlarmStatus', 'VT_Start', 'TagID', 'EventTypeID', 'VT_End', 'H', 'S']

,ServerName,EventID,IntervalIdentifier,Priority,Parameter,FromValue,ToValue,Value,Description,ACTION,...,Limit,LocationFullName,LocationTagName,AlarmStatus,VT_Start,TagID,EventTypeID,VT_End,H,S
0,S1-PROD-ESVT01,46281768,MESSAGE,16,None,None,None,None,20May22 17:31:33 * Completed AM Schedule Data ...,ACK,...,NaN,/Assets/TRAIN_1/1H,1H,None,2022-05-20 19:01:40.205200,$Prsts30,4,None,2022_05_20_19,S1-PROD-ESVT01
1,S1-PROD-ESVT01,31214555,None,16,None,None,None,None,UT ALM RECOV ...,None,...,NaN,/Assets/TRAIN_1/1H,1H,None,2021-10-11 10:32:51.022100,$UNITOPS,4,None,2021_10_11_10,S1-PROD-ESVT01
2,S1-PROD-ESVT01,31214556,None,16,None,None,None,None,UT RECOV CMP ...,None,...,NaN,/Assets/TRAIN_1/1H,1H,None,2021-10-11 10:32:51.022100,$UNITOPS,4,None,2021_10_11_10,S1-PROD-ESVT01

── 1H_AlarmEventsLinked ──
   Shape   : (32728, 29)
   Columns : ['ServerName', 'EventID', 'IntervalIdentifier', 'Priority', 'Parameter', 'FromValue', 'ToValue', 'Value', 'Description', 'ACTION', 'Unit', 'UnitOfMeasure', 'TagName', 'Area', 'Limit', 'LocationFullName', 'LocationTagName', 'AlarmStatus', 'VT_Start', 'TagID', 'EventTypeID', 'VT_End', 'LastEvent', 'NextEvent', 'rowid', 'Seconds', 'PrevSeconds', 'H', 'S']

,ServerName,EventID,IntervalIdentifier,Priority,Parameter,FromValue,ToValue,Value,Description,ACTION,...,TagID,EventTypeID,VT_End,LastEvent,NextEvent,rowid,Seconds,PrevSeconds,H,S
0,S1-PROD-ESVT01,37174405,C1ALM,16,None,None,STEP 1,STEP 1,3C153 STEP TIME EXCEEDED,None,...,03C153_TM_ALM1,1,None,0,2,1,52929,6,2022_02_05_20,S1-PROD-ESVT01
1,S1-PROD-ESVT01,37221043,C1ALM,16,None,None,STEP 1,STEP 1,3C153 STEP TIME EXCEEDED,OK,...,03C153_TM_ALM1,2,None,1,1,2,38016967,52929,2022_02_06_11,S1-PROD-ESVT01
2,S1-PROD-ESVT01,33112793,C2ALM,16,None,None,STEP 2,STEP 2,3C153 STEP TIME EXCEEDED,None,...,03C153_TM_ALM1,1,None,0,2,7,731,6,2021_12_08_05,S1-PROD-ESVT01

── 1I_ChangeEvents ──
   Shape   : (91578, 30)
   Columns : ['Action', 'Actor', 'AreaName', 'AlarmLimit', 'Block', 'Category', 'ConditionName', 'Description', 'EventID', 'Flags', 'LocalTime', 'LocationFullName', 'LocationTagName', 'PrevValue', 'Priority', 'ReceivedDelay', 'ServerName', 'ShelvedReason', 'Source', 'SourceParameter', 'Station', 'Time', 'TransactionID', 'Units', 'Value', 'VT_Start', 'H', 'TagID', 'AlarmStatus', 'S']

,Action,Actor,AreaName,AlarmLimit,Block,Category,ConditionName,Description,EventID,Flags,...,Station,Time,TransactionID,Units,Value,VT_Start,H,TagID,AlarmStatus,S
0,None,None,1I,NaN,None,14,None,PROCESS EVNT RCVRY 1I ...,31214567,NaN,...,None,1974-03-17 20:27:01.794031,31214567,None,None,2021-10-11 10:32:59.403100,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01
1,None,None,1I,NaN,None,14,None,PROCESS EVNT RCVRY 1I ...,31214568,NaN,...,None,1974-03-17 20:27:01.794042,31214568,None,None,2021-10-11 10:32:59.404200,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01
2,None,None,1I,NaN,None,14,None,PROCESS EVNT RCVRY 1I ...,31214569,NaN,...,None,1974-03-17 20:27:01.795147,31214569,None,None,2021-10-11 10:32:59.514700,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01

── 1I_AlarmEvents ──
   Shape   : (54842, 24)
   Columns : ['ServerName', 'EventID', 'IntervalIdentifier', 'Priority', 'Parameter', 'FromValue', 'ToValue', 'Value', 'Description', 'ACTION', 'Unit', 'UnitOfMeasure', 'TagName', 'Area', 'Limit', 'LocationFullName', 'LocationTagName', 'AlarmStatus', 'VT_Start', 'TagID', 'EventTypeID', 'VT_End', 'H', 'S']

,ServerName,EventID,IntervalIdentifier,Priority,Parameter,FromValue,ToValue,Value,Description,ACTION,...,Limit,LocationFullName,LocationTagName,AlarmStatus,VT_Start,TagID,EventTypeID,VT_End,H,S
0,S1-PROD-ESVT01,46282209,MESSAGE,16,None,None,None,None,20May22 17:31:46 * Completed AM Schedule Data ...,ACK,...,NaN,/Assets/TRAIN_1/1I,1I,None,2022-05-20 19:04:29.142800,$Prsts30,4,None,2022_05_20_19,S1-PROD-ESVT01
1,S1-PROD-ESVT01,31214570,None,16,None,None,None,None,UT ALM RECOV ...,None,...,NaN,/Assets/TRAIN_1/1I,1I,None,2021-10-11 10:32:59.514200,$UNITOPS,4,None,2021_10_11_10,S1-PROD-ESVT01
2,S1-PROD-ESVT01,31214571,None,16,None,None,None,None,UT RECOV CMP ...,None,...,NaN,/Assets/TRAIN_1/1I,1I,None,2021-10-11 10:32:59.514200,$UNITOPS,4,None,2021_10_11_10,S1-PROD-ESVT01

── 1I_AlarmEventsLinked ──
   Shape   : (5129, 29)
   Columns : ['ServerName', 'EventID', 'IntervalIdentifier', 'Priority', 'Parameter', 'FromValue', 'ToValue', 'Value', 'Description', 'ACTION', 'Unit', 'UnitOfMeasure', 'TagName', 'Area', 'Limit', 'LocationFullName', 'LocationTagName', 'AlarmStatus', 'VT_Start', 'TagID', 'EventTypeID', 'VT_End', 'LastEvent', 'NextEvent', 'rowid', 'Seconds', 'PrevSeconds', 'H', 'S']

,ServerName,EventID,IntervalIdentifier,Priority,Parameter,FromValue,ToValue,Value,Description,ACTION,...,TagID,EventTypeID,VT_End,LastEvent,NextEvent,rowid,Seconds,PrevSeconds,H,S
0,S1-PROD-ESVT01,47675630,CMDDIS,16,None,None,STOP,STOP,3K151 LO COOLER-A,None,...,03EM_1511A,1,None,0,2,1,9,6,2022_05_28_06,S1-PROD-ESVT01
1,S1-PROD-ESVT01,47675650,CMDDIS,16,None,None,STOP,STOP,3K151 LO COOLER-A,OK,...,03EM_1511A,2,None,1,1,2,26364687,9,2022_05_28_06,S1-PROD-ESVT01
2,S1-PROD-ESVT01,57006067,CMDDIS,16,None,None,STOP,STOP,3K151 LO COOLER-A,None,...,03EM_1511A,1,None,2,2,3,184,26364687,2023_03_29_09,S1-PROD-ESVT01

── 1J_ChangeEvents ──
   Shape   : (90779, 30)
   Columns : ['Action', 'Actor', 'AreaName', 'AlarmLimit', 'Block', 'Category', 'ConditionName', 'Description', 'EventID', 'Flags', 'LocalTime', 'LocationFullName', 'LocationTagName', 'PrevValue', 'Priority', 'ReceivedDelay', 'ServerName', 'ShelvedReason', 'Source', 'SourceParameter', 'Station', 'Time', 'TransactionID', 'Units', 'Value', 'VT_Start', 'H', 'TagID', 'AlarmStatus', 'S']

,Action,Actor,AreaName,AlarmLimit,Block,Category,ConditionName,Description,EventID,Flags,...,Station,Time,TransactionID,Units,Value,VT_Start,H,TagID,AlarmStatus,S
0,None,None,1J,NaN,None,14,None,PROCESS EVNT RCVRY 1J ...,31214585,NaN,...,None,1974-03-17 20:27:01.876022,31214585,None,None,2021-10-11 10:33:07.602200,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01
1,None,None,1J,NaN,None,14,None,PROCESS EVNT RCVRY 1J ...,31214584,NaN,...,None,1974-03-17 20:27:01.876024,31214584,None,None,2021-10-11 10:33:07.602400,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01
2,None,None,1J,NaN,None,14,None,PROCESS EVNT RCVRY 1J ...,31214586,NaN,...,None,1974-03-17 20:27:01.876025,31214586,None,None,2021-10-11 10:33:07.602500,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01

── 1J_AlarmEvents ──
   Shape   : (46413, 24)
   Columns : ['ServerName', 'EventID', 'IntervalIdentifier', 'Priority', 'Parameter', 'FromValue', 'ToValue', 'Value', 'Description', 'ACTION', 'Unit', 'UnitOfMeasure', 'TagName', 'Area', 'Limit', 'LocationFullName', 'LocationTagName', 'AlarmStatus', 'VT_Start', 'TagID', 'EventTypeID', 'VT_End', 'H', 'S']

,ServerName,EventID,IntervalIdentifier,Priority,Parameter,FromValue,ToValue,Value,Description,ACTION,...,Limit,LocationFullName,LocationTagName,AlarmStatus,VT_Start,TagID,EventTypeID,VT_End,H,S
0,S1-PROD-ESVT01,46282210,MESSAGE,16,None,None,None,None,20May22 17:31:59 * Completed AM Schedule Data ...,ACK,...,NaN,/Assets/TRAIN_1/1J,1J,None,2022-05-20 19:04:29.143700,$Prsts30,4,None,2022_05_20_19,S1-PROD-ESVT01
1,S1-PROD-ESVT01,31214589,None,16,None,None,None,None,UT ALM RECOV ...,None,...,NaN,/Assets/TRAIN_1/1J,1J,None,2021-10-11 10:33:08.008600,$UNITOPS,4,None,2021_10_11_10,S1-PROD-ESVT01
2,S1-PROD-ESVT01,31214590,None,16,None,None,None,None,UT RECOV CMP ...,None,...,NaN,/Assets/TRAIN_1/1J,1J,None,2021-10-11 10:33:08.008600,$UNITOPS,4,None,2021_10_11_10,S1-PROD-ESVT01

── 1J_AlarmEventsLinked ──
   Shape   : (3720, 29)
   Columns : ['ServerName', 'EventID', 'IntervalIdentifier', 'Priority', 'Parameter', 'FromValue', 'ToValue', 'Value', 'Description', 'ACTION', 'Unit', 'UnitOfMeasure', 'TagName', 'Area', 'Limit', 'LocationFullName', 'LocationTagName', 'AlarmStatus', 'VT_Start', 'TagID', 'EventTypeID', 'VT_End', 'LastEvent', 'NextEvent', 'rowid', 'Seconds', 'PrevSeconds', 'H', 'S']

,ServerName,EventID,IntervalIdentifier,Priority,Parameter,FromValue,ToValue,Value,Description,ACTION,...,TagID,EventTypeID,VT_End,LastEvent,NextEvent,rowid,Seconds,PrevSeconds,H,S
0,S1-PROD-ESVT01,31576061,BADPV,16,None,None,None,None,3K152 O2 IN BARIER GAS,None,...,03AI_3512,1,None,0,1,1,183808,6,2021_10_28_10,S1-PROD-ESVT01
1,S1-PROD-ESVT01,31620034,BADPV,16,None,None,None,None,3K152 O2 IN BARIER GAS,None,...,03AI_3512,1,None,1,2,2,1656,183808,2021_10_30_13,S1-PROD-ESVT01
2,S1-PROD-ESVT01,31621375,BADPV,16,None,None,None,None,3K152 O2 IN BARIER GAS,OK,...,03AI_3512,2,None,1,1,3,11,1656,2021_10_30_13,S1-PROD-ESVT01

── 1K_ChangeEvents ──
   Shape   : (523768, 30)
   Columns : ['Action', 'Actor', 'AreaName', 'AlarmLimit', 'Block', 'Category', 'ConditionName', 'Description', 'EventID', 'Flags', 'LocalTime', 'LocationFullName', 'LocationTagName', 'PrevValue', 'Priority', 'ReceivedDelay', 'ServerName', 'ShelvedReason', 'Source', 'SourceParameter', 'Station', 'Time', 'TransactionID', 'Units', 'Value', 'VT_Start', 'H', 'TagID', 'AlarmStatus', 'S']

,Action,Actor,AreaName,AlarmLimit,Block,Category,ConditionName,Description,EventID,Flags,...,Station,Time,TransactionID,Units,Value,VT_Start,H,TagID,AlarmStatus,S
0,None,None,1K,NaN,None,14,None,PROCESS EVNT RCVRY 1K ...,31214597,NaN,...,None,1974-03-17 20:27:01.960022,31214597,None,None,2021-10-11 10:33:16.002200,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01
1,None,None,1K,NaN,None,14,None,PROCESS EVNT RCVRY 1K ...,31214595,NaN,...,None,1974-03-17 20:27:01.960024,31214595,None,None,2021-10-11 10:33:16.002400,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01
2,None,None,1K,NaN,None,14,None,PROCESS EVNT RCVRY 1K ...,31214596,NaN,...,None,1974-03-17 20:27:01.960024,31214596,None,None,2021-10-11 10:33:16.002400,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01

── 1K_AlarmEvents ──
   Shape   : (82657, 24)
   Columns : ['ServerName', 'EventID', 'IntervalIdentifier', 'Priority', 'Parameter', 'FromValue', 'ToValue', 'Value', 'Description', 'ACTION', 'Unit', 'UnitOfMeasure', 'TagName', 'Area', 'Limit', 'LocationFullName', 'LocationTagName', 'AlarmStatus', 'VT_Start', 'TagID', 'EventTypeID', 'VT_End', 'H', 'S']

,ServerName,EventID,IntervalIdentifier,Priority,Parameter,FromValue,ToValue,Value,Description,ACTION,...,Limit,LocationFullName,LocationTagName,AlarmStatus,VT_Start,TagID,EventTypeID,VT_End,H,S
0,S1-PROD-ESVT01,46282211,MESSAGE,16,None,None,None,None,20May22 17:32:12 * Completed AM Schedule Data ...,ACK,...,NaN,/Assets/TRAIN_1/1K,1K,None,2022-05-20 19:04:29.144500,$Prsts30,4,None,2022_05_20_19,S1-PROD-ESVT01
1,S1-PROD-ESVT01,31214599,None,16,None,None,None,None,UT ALM RECOV ...,None,...,NaN,/Assets/TRAIN_1/1K,1K,None,2021-10-11 10:33:16.021500,$UNITOPS,4,None,2021_10_11_10,S1-PROD-ESVT01
2,S1-PROD-ESVT01,31214600,None,16,None,None,None,None,UT RECOV CMP ...,None,...,NaN,/Assets/TRAIN_1/1K,1K,None,2021-10-11 10:33:16.021500,$UNITOPS,4,None,2021_10_11_10,S1-PROD-ESVT01

── 1K_AlarmEventsLinked ──
   Shape   : (19819, 29)
   Columns : ['ServerName', 'EventID', 'IntervalIdentifier', 'Priority', 'Parameter', 'FromValue', 'ToValue', 'Value', 'Description', 'ACTION', 'Unit', 'UnitOfMeasure', 'TagName', 'Area', 'Limit', 'LocationFullName', 'LocationTagName', 'AlarmStatus', 'VT_Start', 'TagID', 'EventTypeID', 'VT_End', 'LastEvent', 'NextEvent', 'rowid', 'Seconds', 'PrevSeconds', 'H', 'S']

,ServerName,EventID,IntervalIdentifier,Priority,Parameter,FromValue,ToValue,Value,Description,ACTION,...,TagID,EventTypeID,VT_End,LastEvent,NextEvent,rowid,Seconds,PrevSeconds,H,S
0,S1-PROD-ESVT01,31984604,OFFNORM,16,None,None,OPEN,OPEN,3C155 OVHD VENT VALV,None,...,03EDPV_3420,1,None,0,2,3,203,6,2021_11_25_17,S1-PROD-ESVT01
1,S1-PROD-ESVT01,31984803,OFFNORM,16,None,None,CLOSE,CLOSE,3C155 OVHD VENT VALV,OK,...,03EDPV_3420,2,None,1,1,4,8378809,203,2021_11_25_17,S1-PROD-ESVT01
2,S1-PROD-ESVT01,38316612,OFFNORM,16,None,None,MOVING,MOVING,3C155 OVHD VENT VALV,None,...,03EDPV_3420,1,None,2,2,5,28,8378809,2022_03_02_16,S1-PROD-ESVT01

── 1L_ChangeEvents ──
   Shape   : (1051748, 30)
   Columns : ['Action', 'Actor', 'AreaName', 'AlarmLimit', 'Block', 'Category', 'ConditionName', 'Description', 'EventID', 'Flags', 'LocalTime', 'LocationFullName', 'LocationTagName', 'PrevValue', 'Priority', 'ReceivedDelay', 'ServerName', 'ShelvedReason', 'Source', 'SourceParameter', 'Station', 'Time', 'TransactionID', 'Units', 'Value', 'VT_Start', 'H', 'TagID', 'AlarmStatus', 'S']

,Action,Actor,AreaName,AlarmLimit,Block,Category,ConditionName,Description,EventID,Flags,...,Station,Time,TransactionID,Units,Value,VT_Start,H,TagID,AlarmStatus,S
0,None,None,1L,NaN,None,14,None,PROCESS EVNT RCVRY 1L ...,31214603,NaN,...,None,1974-03-17 20:27:02.044029,31214603,None,None,2021-10-11 10:33:24.402900,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01
1,None,None,1L,NaN,None,14,None,PROCESS EVNT RCVRY 1L ...,31214604,NaN,...,None,1974-03-17 20:27:02.044035,31214604,None,None,2021-10-11 10:33:24.403500,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01
2,None,None,1L,NaN,None,14,None,PROCESS EVNT RCVRY 1L ...,31214605,NaN,...,None,1974-03-17 20:27:02.045100,31214605,None,None,2021-10-11 10:33:24.510000,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01

── 1L_AlarmEvents ──
   Shape   : (86427, 24)
   Columns : ['ServerName', 'EventID', 'IntervalIdentifier', 'Priority', 'Parameter', 'FromValue', 'ToValue', 'Value', 'Description', 'ACTION', 'Unit', 'UnitOfMeasure', 'TagName', 'Area', 'Limit', 'LocationFullName', 'LocationTagName', 'AlarmStatus', 'VT_Start', 'TagID', 'EventTypeID', 'VT_End', 'H', 'S']

,ServerName,EventID,IntervalIdentifier,Priority,Parameter,FromValue,ToValue,Value,Description,ACTION,...,Limit,LocationFullName,LocationTagName,AlarmStatus,VT_Start,TagID,EventTypeID,VT_End,H,S
0,S1-PROD-ESVT01,46282212,MESSAGE,16,None,None,None,None,20May22 17:32:26 * Completed AM Schedule Data ...,ACK,...,NaN,/Assets/TRAIN_1/1L,1L,None,2022-05-20 19:04:29.145400,$Prsts30,4,None,2022_05_20_19,S1-PROD-ESVT01
1,S1-PROD-ESVT01,31214606,None,16,None,None,None,None,UT ALM RECOV ...,None,...,NaN,/Assets/TRAIN_1/1L,1L,None,2021-10-11 10:33:24.509500,$UNITOPS,4,None,2021_10_11_10,S1-PROD-ESVT01
2,S1-PROD-ESVT01,31214607,None,16,None,None,None,None,UT RECOV CMP ...,None,...,NaN,/Assets/TRAIN_1/1L,1L,None,2021-10-11 10:33:24.509500,$UNITOPS,4,None,2021_10_11_10,S1-PROD-ESVT01

── 1L_AlarmEventsLinked ──
   Shape   : (49369, 29)
   Columns : ['ServerName', 'EventID', 'IntervalIdentifier', 'Priority', 'Parameter', 'FromValue', 'ToValue', 'Value', 'Description', 'ACTION', 'Unit', 'UnitOfMeasure', 'TagName', 'Area', 'Limit', 'LocationFullName', 'LocationTagName', 'AlarmStatus', 'VT_Start', 'TagID', 'EventTypeID', 'VT_End', 'LastEvent', 'NextEvent', 'rowid', 'Seconds', 'PrevSeconds', 'H', 'S']

,ServerName,EventID,IntervalIdentifier,Priority,Parameter,FromValue,ToValue,Value,Description,ACTION,...,TagID,EventTypeID,VT_End,LastEvent,NextEvent,rowid,Seconds,PrevSeconds,H,S
0,S1-PROD-ESVT01,32781538,CMDDIS,16,None,None,BAD,BAD,3K101 ESD VENT VALV,None,...,03EDPV_1153,1,None,0,2,1,1452,6,2021_12_04_19,S1-PROD-ESVT01
1,S1-PROD-ESVT01,32783017,CMDDIS,16,None,None,CLOSE,CLOSE,3K101 ESD VENT VALV,OK,...,03EDPV_1153,2,None,1,1,2,2065,1452,2021_12_04_19,S1-PROD-ESVT01
2,S1-PROD-ESVT01,32784906,CMDDIS,16,None,None,CLOSE,CLOSE,3K101 ESD VENT VALV,None,...,03EDPV_1153,1,None,2,2,3,120,2065,2021_12_04_20,S1-PROD-ESVT01

── 3I_ChangeEvents ──
   Shape   : (388599, 30)
   Columns : ['Action', 'Actor', 'AreaName', 'AlarmLimit', 'Block', 'Category', 'ConditionName', 'Description', 'EventID', 'Flags', 'LocalTime', 'LocationFullName', 'LocationTagName', 'PrevValue', 'Priority', 'ReceivedDelay', 'ServerName', 'ShelvedReason', 'Source', 'SourceParameter', 'Station', 'Time', 'TransactionID', 'Units', 'Value', 'VT_Start', 'H', 'TagID', 'AlarmStatus', 'S']

,Action,Actor,AreaName,AlarmLimit,Block,Category,ConditionName,Description,EventID,Flags,...,Station,Time,TransactionID,Units,Value,VT_Start,H,TagID,AlarmStatus,S
0,None,None,3I,NaN,None,14,None,PROCESS EVNT RCVRY 3I ...,31214683,NaN,...,None,1974-03-17 20:27:02.464027,31214683,None,None,2021-10-11 10:34:06.402700,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01
1,None,None,3I,NaN,None,14,None,PROCESS EVNT RCVRY 3I ...,31214681,NaN,...,None,1974-03-17 20:27:02.464032,31214681,None,None,2021-10-11 10:34:06.403200,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01
2,None,None,3I,NaN,None,14,None,PROCESS EVNT RCVRY 3I ...,31214682,NaN,...,None,1974-03-17 20:27:02.464033,31214682,None,None,2021-10-11 10:34:06.403300,2021_10_11_10,$CONSOLE01,None,S1-PROD-ESVT01

── 3I_AlarmEvents ──
   Shape   : (56023, 24)
   Columns : ['ServerName', 'EventID', 'IntervalIdentifier', 'Priority', 'Parameter', 'FromValue', 'ToValue', 'Value', 'Description', 'ACTION', 'Unit', 'UnitOfMeasure', 'TagName', 'Area', 'Limit', 'LocationFullName', 'LocationTagName', 'AlarmStatus', 'VT_Start', 'TagID', 'EventTypeID', 'VT_End', 'H', 'S']

,ServerName,EventID,IntervalIdentifier,Priority,Parameter,FromValue,ToValue,Value,Description,ACTION,...,Limit,LocationFullName,LocationTagName,AlarmStatus,VT_Start,TagID,EventTypeID,VT_End,H,S
0,S1-PROD-ESVT01,39053520,None,16,None,None,None,None,UT ALM RECOV ...,None,...,NaN,/Assets/TRAIN_2/3I,3I,None,2022-03-24 12:35:31.853400,$UNITOPS,4,None,2022_03_24_12,S1-PROD-ESVT01
1,S1-PROD-ESVT01,39053521,None,16,None,None,None,None,UT RECOV CMP ...,None,...,NaN,/Assets/TRAIN_2/3I,3I,None,2022-03-24 12:35:31.853400,$UNITOPS,4,None,2022_03_24_12,S1-PROD-ESVT01
2,S1-PROD-ESVT01,74400276,CHANGE,16,None,None,ALL,ALL,PVSRCOPT,None,...,NaN,/Assets/TRAIN_2/3I,3I,None,2024-12-05 11:48:00.436300,01CR_3H05_DI22,4,None,2024_12_05_11,S1-PROD-ESVT01

── 3I_AlarmEventsLinked ──
   Shape   : (16142, 29)
   Columns : ['ServerName', 'EventID', 'IntervalIdentifier', 'Priority', 'Parameter', 'FromValue', 'ToValue', 'Value', 'Description', 'ACTION', 'Unit', 'UnitOfMeasure', 'TagName', 'Area', 'Limit', 'LocationFullName', 'LocationTagName', 'AlarmStatus', 'VT_Start', 'TagID', 'EventTypeID', 'VT_End', 'LastEvent', 'NextEvent', 'rowid', 'Seconds', 'PrevSeconds', 'H', 'S']

,ServerName,EventID,IntervalIdentifier,Priority,Parameter,FromValue,ToValue,Value,Description,ACTION,...,TagID,EventTypeID,VT_End,LastEvent,NextEvent,rowid,Seconds,PrevSeconds,H,S
0,S1-PROD-ESVT01,61724101,CMDDIS,16,None,None,STOP,STOP,3G122 LUBE OIL COOLER,None,...,03EM_1003,1,None,0,2,1,12,6,2023_06_20_12,S1-PROD-ESVT01
1,S1-PROD-ESVT01,61724112,CMDDIS,16,None,None,RUN,RUN,3G122 LUBE OIL COOLER,OK,...,03EM_1003,2,None,1,1,2,3793062,12,2023_06_20_12,S1-PROD-ESVT01
2,S1-PROD-ESVT01,62980123,CMDDIS,16,None,None,STOP,STOP,3G122 LUBE OIL COOLER,None,...,03EM_1003,1,None,2,2,3,14,3793062,2023_08_03_10,S1-PROD-ESVT01

## 8. Summary

In [13]:
print(f"{'='*60}")
print(f"  SUMMARY for target tag: {TARGET_TAG}")
print(f"{'='*60}")
print(f"  Related tags in sheet         : {len(df_tags)}")
print(f"  Unique assets referenced      : {len(df_asset_map)}")
print(f"  Assets found in Historian/    : {df_availability['In Historian/'].sum()}")
print(f"  Assets found in events/       : {df_availability['In events/'].sum()}")
print(f"  Historian series loaded       : {len(historian_data)}")
print(f"  Event tables loaded           : {len(events_data)}")
print(f"{'='*60}")
print()
print("Historian series:")
for k, v in historian_data.items():
    print(f"  {k:35s}  {v.shape[0]:>8,} rows")
print()
print("Event tables:")
for k, v in events_data.items():
    print(f"  {k:45s}  {v.shape[0]:>8,} rows")

============================================================
  SUMMARY for target tag: 03PIC_1104
============================================================
  Related tags in sheet         : 36
  Unique assets referenced      : 8
  Assets found in Historian/    : 8
  Assets found in events/       : 8
  Historian series loaded       : 30
  Event tables loaded           : 24
============================================================

Historian series:
  02FI_1000.PV                         2,130,628 rows
  03TI_1408.PV                         2,169,302 rows
  03PIC_1068.PV                        2,169,275 rows
  03PIC_1104.PV                        2,169,275 rows
  03TI_1427.PV                         2,169,291 rows
  03TI_1099.PV                         2,169,306 rows
  03TI_1100.PV                         2,169,306 rows
  03TI_1101.PV                         2,169,306 rows
  03TI_1102.PV                         2,169,305 rows
  03LIC_1071.PV                        2,168,639 rows
  03FIC_1085.PV                        2,144,381 rows
  03LIC_1094.PV                        2,169,306 rows
  03LIC_1097.PV                        2,169,291 rows
  03FI_1105.PV                         2,169,275 rows
  03PIC_3131.PV                        2,134,282 rows
  03PIC_3002.PV                        2,134,282 rows
  03PIC_3000.PV                        2,134,281 rows
  03TIC_3008.PV                        2,134,293 rows
  03FIC_3000.PV                        2,134,275 rows
  03PDI_3011.PV                        2,134,281 rows
  03TIC_3014.PV                        2,134,294 rows
  03TI_3016.PV                         2,133,839 rows
  03PI_3017.PV                         2,134,282 rows
  03LIC_3153.PV                        2,169,301 rows
  03LIC_3178.PV                        2,091,336 rows
  03FIC_3435.PV                        2,167,054 rows
  03FI_3173.PV                         2,169,274 rows
  03FI_3188.PV                         2,169,274 rows
  03FI_1141A.PV                        2,096,863 rows
  03FIC_1474.PV                        2,108,675 rows

Event tables:
  1A_ChangeEvents                                2,507,555 rows
  1A_AlarmEvents                                   54,844 rows
  1A_AlarmEventsLinked                            201,117 rows
  1F_ChangeEvents                                 138,249 rows
  1F_AlarmEvents                                   44,033 rows
  1F_AlarmEventsLinked                             19,238 rows
  1H_ChangeEvents                                 277,370 rows
  1H_AlarmEvents                                   83,813 rows
  1H_AlarmEventsLinked                             32,728 rows
  1I_ChangeEvents                                  91,578 rows
  1I_AlarmEvents                                   54,842 rows
  1I_AlarmEventsLinked                              5,129 rows
  1J_ChangeEvents                                  90,779 rows
  1J_AlarmEvents                                   46,413 rows
  1J_AlarmEventsLinked                              3,720 rows
  1K_ChangeEvents                                 523,768 rows
  1K_AlarmEvents                                   82,657 rows
  1K_AlarmEventsLinked                             19,819 rows
  1L_ChangeEvents                                1,051,748 rows
  1L_AlarmEvents                                   86,427 rows
  1L_AlarmEventsLinked                             49,369 rows
  3I_ChangeEvents                                 388,599 rows
  3I_AlarmEvents                                   56,023 rows
  3I_AlarmEventsLinked                             16,142 rows

## 9. Combine All Events and Save

Concatenate all event tables (`_E`, `_EA`, `_EAL`) for all assets into a single DataFrame,
add a `source_table` column to track the origin, sort by `VT_Start`, and save to
`DATA/combined_events/<TARGET_TAG>_combined_events.parquet`.

In [14]:
import os

# ── Output directory ────────────────────────────────────────────────────────────
OUTPUT_DIR = os.path.join(DATA_DIR, 'combined_events')
os.makedirs(OUTPUT_DIR, exist_ok=True)
print(f"Output directory : {OUTPUT_DIR}")
print()

# ── Concatenate all event DataFrames ────────────────────────────────────────────
print(f"Concatenating {len(events_data)} event tables ...\n")

parts = []
for table_key, df_part in events_data.items():
    df_part = df_part.copy()
    df_part['source_table'] = table_key          # track origin: e.g. '1E_AlarmEvents'
    parts.append(df_part)
    print(f"  + {table_key:45s}  {len(df_part):>9,} rows  |  "
          f"VT_Start range: {df_part['VT_Start'].min()}  →  {df_part['VT_Start'].max()}")

df_combined = pd.concat(parts, ignore_index=True, sort=False)

print(f"\nRaw combined shape : {df_combined.shape}")
print(f"Columns            : {df_combined.columns.tolist()}")

# ── Apply timezone offset ─────────────────────────────────────────────────────────
# Historian events are stored in UTC+5:30 (IST); plant PV data is in UTC+4 (UAE local).
# Subtract 1.5 hours to align event timestamps with the PV time series.
TIME_OFFSET = pd.Timedelta(hours=1.5)
print(f"\nApplying timezone offset: VT_Start -= {TIME_OFFSET} (UTC+5:30 → UAE local UTC+4)")
print(f"  VT_Start before: {df_combined['VT_Start'].min()}  →  {df_combined['VT_Start'].max()}")
df_combined['VT_Start'] = df_combined['VT_Start'] - TIME_OFFSET
print(f"  VT_Start after : {df_combined['VT_Start'].min()}  →  {df_combined['VT_Start'].max()}")

# ── Sort by VT_Start ─────────────────────────────────────────────────────────────
print(f"\nSorting by VT_Start ...")
df_combined.sort_values('VT_Start', inplace=True, ignore_index=True)

print(f"Sorted combined shape : {df_combined.shape}")
print(f"VT_Start range        : {df_combined['VT_Start'].min()}  →  {df_combined['VT_Start'].max()}")
print(f"Null VT_Start rows    : {df_combined['VT_Start'].isna().sum():,}")

# ── Save ─────────────────────────────────────────────────────────────────────────
output_path = os.path.join(OUTPUT_DIR, f"{TARGET_TAG}_combined_events.parquet")
df_combined.to_parquet(output_path, index=False)
file_size_mb = os.path.getsize(output_path) / (1024 ** 2)

print(f"\n{'='*60}")
print(f"  Saved to : {output_path}")
print(f"  Rows     : {len(df_combined):,}")
print(f"  Columns  : {len(df_combined.columns)}")
print(f"  File size: {file_size_mb:.1f} MB")
print(f"{'='*60}")
print(f"\nsource_table breakdown:")
print(df_combined['source_table'].value_counts().to_string())

Output directory : /home/h604827/ControlActions/DATA/combined_events

Concatenating 24 event tables ...

  + 1A_ChangeEvents                                2,507,555 rows  |  VT_Start range: 2021-02-01 17:19:41.804300  →  2025-06-28 00:22:59.137300
  + 1A_AlarmEvents                                    54,844 rows  |  VT_Start range: 2021-10-02 14:30:37.668800  →  2025-06-27 18:53:34.052000
  + 1A_AlarmEventsLinked                             201,117 rows  |  VT_Start range: 2021-10-09 09:58:38.952700  →  2025-06-03 10:22:26.768300
  + 1F_ChangeEvents                                  138,249 rows  |  VT_Start range: 2021-10-03 12:00:59.953200  →  2025-06-27 20:14:25.077400
  + 1F_AlarmEvents                                    44,033 rows  |  VT_Start range: 2021-10-03 12:08:23.078500  →  2025-06-27 16:57:51.410300
  + 1F_AlarmEventsLinked                              19,238 rows  |  VT_Start range: 2021-10-03 12:00:59.953200  →  2025-06-27 20:14:25.077400
  + 1H_ChangeEvents                                  277,370 rows  |  VT_Start range: 2021-02-04 16:57:51.852700  →  2025-06-28 03:26:39.783700
  + 1H_AlarmEvents                                    83,813 rows  |  VT_Start range: 2021-10-02 12:25:55.765200  →  2025-06-28 03:26:39.783700
  + 1H_AlarmEventsLinked                              32,728 rows  |  VT_Start range: 2021-02-04 16:57:51.852700  →  2025-06-28 03:25:54.980600
  + 1I_ChangeEvents                                   91,578 rows  |  VT_Start range: 2021-10-02 14:05:18.602600  →  2025-06-27 19:33:06.456000
  + 1I_AlarmEvents                                    54,842 rows  |  VT_Start range: 2021-10-02 14:09:07.465900  →  2025-06-27 17:28:05.401283
  + 1I_AlarmEventsLinked                               5,129 rows  |  VT_Start range: 2021-10-02 14:05:18.602600  →  2025-06-27 10:57:24.099500
  + 1J_ChangeEvents                                   90,779 rows  |  VT_Start range: 2021-10-02 11:27:18.303600  →  2025-06-28 05:03:45.141400
  + 1J_AlarmEvents                                    46,413 rows  |  VT_Start range: 2021-10-11 10:33:08.008600  →  2025-06-26 16:16:50.847800
  + 1J_AlarmEventsLinked                               3,720 rows  |  VT_Start range: 2021-10-28 10:01:01.202900  →  2025-06-18 19:06:48.337300
  + 1K_ChangeEvents                                  523,768 rows  |  VT_Start range: 2021-10-02 10:19:05.611200  →  2025-06-28 00:04:17.656000
  + 1K_AlarmEvents                                    82,657 rows  |  VT_Start range: 2021-10-02 10:19:05.611200  →  2025-06-28 00:04:17.656000
  + 1K_AlarmEventsLinked                              19,819 rows  |  VT_Start range: 2021-10-10 17:35:29.202400  →  2025-06-01 07:23:13.522000
  + 1L_ChangeEvents                                1,051,748 rows  |  VT_Start range: 2021-09-06 14:03:15.353100  →  2025-06-27 19:51:07.686300
  + 1L_AlarmEvents                                    86,427 rows  |  VT_Start range: 2021-10-02 05:45:54.804900  →  2025-06-27 16:53:59.018300
  + 1L_AlarmEventsLinked                              49,369 rows  |  VT_Start range: 2021-09-06 14:03:15.353100  →  2025-06-27 19:51:07.686300
  + 3I_ChangeEvents                                  388,599 rows  |  VT_Start range: 2021-10-03 14:32:38.852800  →  2025-06-28 05:28:49.029000
  + 3I_AlarmEvents                                    56,023 rows  |  VT_Start range: 2021-10-03 14:34:34.716800  →  2025-06-28 04:53:43.659300
  + 3I_AlarmEventsLinked                              16,142 rows  |  VT_Start range: 2021-10-03 14:32:38.852800  →  2025-06-27 10:14:49.539900

Raw combined shape : (5925960, 48)
Columns            : ['Action', 'Actor', 'AreaName', 'AlarmLimit', 'Block', 'Category', 'ConditionName', 'Description', 'EventID', 'Flags', 'LocalTime', 'LocationFullName', 'LocationTagName', 'PrevValue', 'Priority', 'ReceivedDelay', 'ServerName', 'ShelvedReason', 'Source', 'SourceParameter', 'Station', 'Time', 'TransactionID', 'Units', 'Value', 'VT_Start', 'H', 'TagID', 'AlarmStatus', 'S', 'source_table', 'IntervalIdentifier', 'Parameter', 'FromValue', 'ToValue', 'ACTION', 'Unit', 'UnitOfMeasure', 'TagName', 'Area', 'Limit', 'EventTypeID', 'VT_End', 'LastEvent', 'NextEvent', 'rowid', 'Seconds', 'PrevSeconds']

Applying timezone offset: VT_Start -= 0 days 01:30:00 (UTC+5:30 → UAE local UTC+4)
  VT_Start before: 2021-02-01 17:19:41.804300  →  2025-06-28 05:28:49.029000
  VT_Start after : 2021-02-01 15:49:41.804300  →  2025-06-28 03:58:49.029000

Sorting by VT_Start ...
Sorted combined shape : (5925960, 48)
VT_Start range        : 2021-02-01 15:49:41.804300  →  2025-06-28 03:58:49.029000
Null VT_Start rows    : 0

============================================================
  Saved to : /home/h604827/ControlActions/DATA/combined_events/03PIC_1104_combined_events.parquet
  Rows     : 5,925,960
  Columns  : 48
  File size: 154.6 MB
============================================================

source_table breakdown:
source_table
1A_ChangeEvents         2507555
1L_ChangeEvents         1051748
1K_ChangeEvents          523768
3I_ChangeEvents          388599
1H_ChangeEvents          277370
1A_AlarmEventsLinked     201117
1F_ChangeEvents          138249
1I_ChangeEvents           91578
1J_ChangeEvents           90779
1L_AlarmEvents            86427
1H_AlarmEvents            83813
1K_AlarmEvents            82657
3I_AlarmEvents            56023
1A_AlarmEvents            54844
1I_AlarmEvents            54842
1L_AlarmEventsLinked      49369
1J_AlarmEvents            46413
1F_AlarmEvents            44033
1H_AlarmEventsLinked      32728
1K_AlarmEventsLinked      19819
1F_AlarmEventsLinked      19238
3I_AlarmEventsLinked      16142
1I_AlarmEventsLinked       5129
1J_AlarmEventsLinked       3720

## 10. Batch Processing — All Tags

Processes **all alarm-tag sheets** from the Excel workbook (from the first tag sheet through to `03PI_1655_PVHI`).

For each sheet:
- The alarm type (`PVLO`, `PVHI`, `PVLO_PVHI`, `AOA`) is inferred from the sheet name.
- Sheets with no valid `ASSET ID` values are skipped automatically.
- Generic non-alarm sheets (`Sheet`, `Sheet1`, `Sheet2`) are skipped.
- Output files are named `{TAG}_{ALARM_TYPE}_combined_events.parquet` and saved to `DATA/combined_events/`.
- Files that already exist are skipped (set `SKIP_EXISTING = False` to re-process them).

In [3]:
import re

# ── Batch config ────────────────────────────────────────────────────────────────
STOP_SHEET    = '03PI_1655_PVHI'    # last sheet to process (inclusive)
SKIP_EXISTING = True                 # set False to re-process already-saved files

# Generic sheets that do not correspond to alarm tags
SKIP_SHEETS = {'Tag List', 'Sheet', 'Sheet1', 'Sheet2'}

# Asset IDs that are invalid / placeholder values
INVALID_ASSET_IDS = {'nan', 'NO', '', 'none'}


def parse_sheet_name(sheet_name):
    """
    Infer (tag, alarm_type) from a sheet name.

    Handles both space- and underscore-separated suffixes, e.g.:
      '03TIC_1023 PVLO_PVHI'  →  ('03TIC_1023', 'PVLO_PVHI')
      '03TIC_1009_PVLO'       →  ('03TIC_1009', 'PVLO')
      '03LIC1608_PVLO'        →  ('03LIC1608',  'PVLO')
      '03LIC_1094'            →  ('03LIC_1094',  None)
    """
    # Check longer alarm types first to avoid PVLO_PVHI matching as PVLO
    for alarm_type in ('PVLO_PVHI', 'PVLO', 'PVHI', 'AOA'):
        for sep in (' ', '_'):
            suffix = sep + alarm_type
            if sheet_name.endswith(suffix):
                return sheet_name[: -len(suffix)].strip(), alarm_type
    return sheet_name.strip(), None


# ── Discover sheets to process ──────────────────────────────────────────────────
_wb = openpyxl.load_workbook(EXCEL_FILE, read_only=True, data_only=True)
_all_sheets = _wb.sheetnames
_wb.close()

_stop_idx = _all_sheets.index(STOP_SHEET) if STOP_SHEET in _all_sheets else len(_all_sheets) - 1
# Skip the very first sheet ('Tag List') and stop at STOP_SHEET (inclusive)
_candidate_sheets = [s for s in _all_sheets[1:_stop_idx + 1] if s not in SKIP_SHEETS]

print(f"Candidate sheets to process : {len(_candidate_sheets)}")
for _s in _candidate_sheets:
    _t, _a = parse_sheet_name(_s)
    _alarm_suffix = f'_{_a}' if _a else ''
    _fname = f"{_t}{_alarm_suffix}_combined_events.parquet"
    _exists = os.path.exists(os.path.join(DATA_DIR, 'combined_events', _fname))
    print(f"  {'[EXISTS]' if _exists else '        ':10s}  {_s!r:38s}  →  {_fname}")

Candidate sheets to process : 19
              '03TIC_1023 PVLO_PVHI'                  →  03TIC_1023_PVLO_PVHI_combined_events.parquet
              '03TIC_1635 PVLO'                       →  03TIC_1635_PVLO_combined_events.parquet
              '03TIC_1009_PVLO'                       →  03TIC_1009_PVLO_combined_events.parquet
              '03TIC_1009_PVHI'                       →  03TIC_1009_PVHI_combined_events.parquet
              '03LIC_1619 PVLO_PVHI'                  →  03LIC_1619_PVLO_PVHI_combined_events.parquet
              '03TIC_1635_PVHI'                       →  03TIC_1635_PVHI_combined_events.parquet
              '03FIC_1668 PVHI'                       →  03FIC_1668_PVHI_combined_events.parquet
              '03PIC_1104 PVHI'                       →  03PIC_1104_PVHI_combined_events.parquet
              '03PIC1023 PVLO_PVHI'                   →  03PIC1023_PVLO_PVHI_combined_events.parquet
              '03TIC_1145 PVLO'                       →  03TIC_1145_PVLO_combined_events.parquet
              '03LIC_1071 PVHI'                       →  03LIC_1071_PVHI_combined_events.parquet
              '03LIC_1016 PVLO_PVHI'                  →  03LIC_1016_PVLO_PVHI_combined_events.parquet
              '03TI_1081 PVHI'                        →  03TI_1081_PVHI_combined_events.parquet
              '03LIC_1094'                            →  03LIC_1094_combined_events.parquet
              '03PI_1814 PVHI'                        →  03PI_1814_PVHI_combined_events.parquet
              '03PIC_1013 PVLO'                       →  03PIC_1013_PVLO_combined_events.parquet
              '03TIC_1745A PVHI'                      →  03TIC_1745A_PVHI_combined_events.parquet
              '03LIC1608_PVLO'                        →  03LIC1608_PVLO_combined_events.parquet
              '03PI_1655_PVHI'                        →  03PI_1655_PVHI_combined_events.parquet

In [ ]:
# import traceback

# # ── Load ADNOC-B.json once (reuse asset_id_to_uuid if already loaded) ───────────
# with open(ADNOC_JSON, 'r') as f:
#     _asset_nodes = json.load(f)
# _asset_id_to_uuid = {n['Name']: {'uuid': n['Id'], 'hierarchy': n['Hierarchy']} for n in _asset_nodes}

# _hist_folders   = set(os.listdir(HISTORIAN_DIR))
# _events_folders = set(os.listdir(EVENTS_DIR))

# OUTPUT_DIR   = os.path.join(DATA_DIR, 'combined_events')
# os.makedirs(OUTPUT_DIR, exist_ok=True)

# TIME_OFFSET  = pd.Timedelta(hours=1.5)

# _KEEP_COLS = ['Potential Input parameter', 'DCS Tag Name', 'DESCRIPTION',
#               'PARAMETER', 'IS DATA AVAILABLE?', 'ASSET ID']

# batch_summary = []

# for _sheet_name in _candidate_sheets:
#     _tag, _alarm_type = parse_sheet_name(_sheet_name)
#     _alarm_suffix  = f'_{_alarm_type}' if _alarm_type else ''
#     _out_filename  = f"{_tag}{_alarm_suffix}_combined_events.parquet"
#     _out_path      = os.path.join(OUTPUT_DIR, _out_filename)

#     # ── Skip if output already exists ─────────────────────────────────────────────
#     if SKIP_EXISTING and os.path.exists(_out_path):
#         _mb = os.path.getsize(_out_path) / (1024 ** 2)
#         print(f"[SKIP  ] {_sheet_name!r:38s}  →  already exists ({_mb:.1f} MB)")
#         batch_summary.append({'Sheet': _sheet_name, 'Tag': _tag, 'AlarmType': _alarm_type,
#                                'Status': 'SKIPPED (exists)', 'Rows': None, 'File': _out_filename})
#         continue

#     print(f"\n{'='*72}")
#     print(f"  Sheet : {_sheet_name!r}")
#     print(f"  Tag   : {_tag}   AlarmType: {_alarm_type}   Output: {_out_filename}")
#     print(f"{'='*72}")

#     try:
#         # ── Read sheet ─────────────────────────────────────────────────────────────
#         _df_sheet = pd.read_excel(EXCEL_FILE, sheet_name=_sheet_name, header=EXCEL_HEADER_ROW)

#         if 'ASSET ID' not in _df_sheet.columns or 'DCS Tag Name' not in _df_sheet.columns:
#             print(f"  [SKIP] Required columns (ASSET ID / DCS Tag Name) not found")
#             batch_summary.append({'Sheet': _sheet_name, 'Tag': _tag, 'AlarmType': _alarm_type,
#                                    'Status': 'SKIP (missing cols)', 'Rows': None, 'File': None})
#             continue

#         _avail_cols = [c for c in _KEEP_COLS if c in _df_sheet.columns]
#         _df_tags_b = (_df_sheet[_avail_cols]
#                       .dropna(subset=['DCS Tag Name'])
#                       .copy())
#         _df_tags_b['DCS Tag Name'] = _df_tags_b['DCS Tag Name'].astype(str).str.strip()
#         _df_tags_b['ASSET ID']     = _df_tags_b['ASSET ID'].astype(str).str.strip()
#         # Filter out invalid / blank asset IDs
#         _df_tags_b = _df_tags_b[~_df_tags_b['ASSET ID'].str.lower().isin(INVALID_ASSET_IDS)]
#         _df_tags_b = _df_tags_b.reset_index(drop=True)

#         if _df_tags_b.empty:
#             print(f"  [SKIP] No valid ASSET IDs found in sheet")
#             batch_summary.append({'Sheet': _sheet_name, 'Tag': _tag, 'AlarmType': _alarm_type,
#                                    'Status': 'SKIP (no assets)', 'Rows': None, 'File': None})
#             continue

#         _unique_assets = sorted(_df_tags_b['ASSET ID'].unique())
#         print(f"  Asset IDs : {_unique_assets}")

#         # ── Map asset names → UUIDs ────────────────────────────────────────────────
#         _asset_map_rows = []
#         for _an in _unique_assets:
#             if _an in _asset_id_to_uuid:
#                 _info = _asset_id_to_uuid[_an]
#                 _asset_map_rows.append({'Asset Name': _an, 'UUID': _info['uuid'],
#                                         'Hierarchy': _info['hierarchy']})
#             else:
#                 print(f"    [WARN] Asset '{_an}' not found in ADNOC-B.json — skipping")
#                 _asset_map_rows.append({'Asset Name': _an, 'UUID': None, 'Hierarchy': None})
#         _df_am = pd.DataFrame(_asset_map_rows)

#         # Merge UUID back to df_tags_b
#         _df_tags_b = _df_tags_b.merge(
#             _df_am.rename(columns={'Asset Name': 'ASSET ID'})[['ASSET ID', 'UUID']],
#             on='ASSET ID', how='left')

#         # ── Load events data ───────────────────────────────────────────────────────
#         _events_data_b = {}
#         for _, _arow in _df_am.iterrows():
#             _uuid  = _arow['UUID']
#             _aname = _arow['Asset Name']
#             if not _uuid or _uuid not in _events_folders:
#                 continue
#             _aev_dir = os.path.join(EVENTS_DIR, _uuid)
#             _aev_files = os.listdir(_aev_dir)
#             for _suf, _lbl in [('_E.parquet',   'ChangeEvents'),
#                                 ('_EA.parquet',  'AlarmEvents'),
#                                 ('_EAL.parquet', 'AlarmEventsLinked')]:
#                 _m = [f for f in _aev_files if f.endswith(_suf)]
#                 if _m:
#                     _df_ev = pd.read_parquet(os.path.join(_aev_dir, _m[0]))
#                     for _ts_col in ['VT_Start', 'Time', 'timestamp']:
#                         if _ts_col in _df_ev.columns:
#                             _df_ev[_ts_col] = pd.to_datetime(_df_ev[_ts_col], format='mixed')
#                     _events_data_b[f"{_aname}_{_lbl}"] = _df_ev

#         print(f"  Event tables loaded : {len(_events_data_b)}")

#         if not _events_data_b:
#             print(f"  [SKIP] No event parquet files found for any asset")
#             batch_summary.append({'Sheet': _sheet_name, 'Tag': _tag, 'AlarmType': _alarm_type,
#                                    'Status': 'SKIP (no events)', 'Rows': None, 'File': None})
#             continue

#         # ── Concatenate ────────────────────────────────────────────────────────────
#         _parts = []
#         for _tkey, _dfp in _events_data_b.items():
#             _dfp = _dfp.copy()
#             _dfp['source_table'] = _tkey
#             _parts.append(_dfp)

#         _df_combined = pd.concat(_parts, ignore_index=True, sort=False)

#         # Apply timezone offset (UTC+5:30 → UAE local UTC+4, i.e. subtract 1.5 h)
#         _df_combined['VT_Start'] = _df_combined['VT_Start'] - TIME_OFFSET
#         _df_combined.sort_values('VT_Start', inplace=True, ignore_index=True)

#         # ── Save ───────────────────────────────────────────────────────────────────
#         _df_combined.to_parquet(_out_path, index=False)
#         _mb = os.path.getsize(_out_path) / (1024 ** 2)
#         print(f"  ✓ Saved  {_out_filename}  ({len(_df_combined):,} rows, {_mb:.1f} MB)")
#         batch_summary.append({'Sheet': _sheet_name, 'Tag': _tag, 'AlarmType': _alarm_type,
#                                'Status': 'OK', 'Rows': len(_df_combined), 'File': _out_filename})

#     except Exception as _ex:
#         print(f"  [ERROR] {_ex}")
#         traceback.print_exc()
#         batch_summary.append({'Sheet': _sheet_name, 'Tag': _tag, 'AlarmType': _alarm_type,
#                                'Status': f'ERROR: {_ex}', 'Rows': None, 'File': None})

# # ── Final summary ──────────────────────────────────────────────────────────────
# print(f"\n{'='*72}")
# print(f"  BATCH COMPLETE  —  {len(batch_summary)} sheets processed")
# print(f"{'='*72}")
# df_batch_summary = pd.DataFrame(batch_summary)
# display(df_batch_summary)

========================================================================
  Sheet : '03TIC_1023 PVLO_PVHI'
  Tag   : 03TIC_1023   AlarmType: PVLO_PVHI   Output: 03TIC_1023_PVLO_PVHI_combined_events.parquet
========================================================================
  Asset IDs : ['1A', '1D', '1E', '1F', '1I', '1L']
  Event tables loaded : 18
  ✓ Saved  03TIC_1023_PVLO_PVHI_combined_events.parquet  (4,587,437 rows, 119.5 MB)

========================================================================
  Sheet : '03TIC_1635 PVLO'
  Tag   : 03TIC_1635   AlarmType: PVLO   Output: 03TIC_1635_PVLO_combined_events.parquet
========================================================================
  Asset IDs : ['1A', '1E', '1F', '1H', '1O']
  Event tables loaded : 15
  ✓ Saved  03TIC_1635_PVLO_combined_events.parquet  (3,866,251 rows, 100.3 MB)

========================================================================
  Sheet : '03TIC_1009_PVLO'
  Tag   : 03TIC_1009   AlarmType: PVLO   Output: 03TIC_1009_PVLO_combined_events.parquet
========================================================================
  Asset IDs : ['1A', '1D', '1E', '1F', '1K']
  Event tables loaded : 15
  ✓ Saved  03TIC_1009_PVLO_combined_events.parquet  (3,874,588 rows, 98.3 MB)

========================================================================
  Sheet : '03TIC_1009_PVHI'
  Tag   : 03TIC_1009   AlarmType: PVHI   Output: 03TIC_1009_PVHI_combined_events.parquet
========================================================================
  Asset IDs : ['1A', '1D', '1E', '1F', '1K']
  Event tables loaded : 15
  ✓ Saved  03TIC_1009_PVHI_combined_events.parquet  (3,874,588 rows, 98.3 MB)

========================================================================
  Sheet : '03LIC_1619 PVLO_PVHI'
  Tag   : 03LIC_1619   AlarmType: PVLO_PVHI   Output: 03LIC_1619_PVLO_PVHI_combined_events.parquet
========================================================================
  Asset IDs : ['1A', '1O']
  Event tables loaded : 6
  ✓ Saved  03LIC_1619_PVLO_PVHI_combined_events.parquet  (3,021,947 rows, 76.1 MB)

========================================================================
  Sheet : '03TIC_1635_PVHI'
  Tag   : 03TIC_1635   AlarmType: PVHI   Output: 03TIC_1635_PVHI_combined_events.parquet
========================================================================
  Asset IDs : ['1A', '1E', '1F', '1H', '1O']
  Event tables loaded : 15
  ✓ Saved  03TIC_1635_PVHI_combined_events.parquet  (3,866,251 rows, 100.3 MB)

========================================================================
  Sheet : '03FIC_1668 PVHI'
  Tag   : 03FIC_1668   AlarmType: PVHI   Output: 03FIC_1668_PVHI_combined_events.parquet
========================================================================
  Asset IDs : ['1A', '1E', '1G', '1H', '1O']
  Event tables loaded : 15
  ✓ Saved  03FIC_1668_PVHI_combined_events.parquet  (4,005,637 rows, 103.3 MB)

========================================================================
  Sheet : '03PIC_1104 PVHI'
  Tag   : 03PIC_1104   AlarmType: PVHI   Output: 03PIC_1104_PVHI_combined_events.parquet
========================================================================
  Asset IDs : ['1A', '1F', '1H', '1I', '1J', '1K', '1L', '3I']
  Event tables loaded : 24
  ✓ Saved  03PIC_1104_PVHI_combined_events.parquet  (5,925,960 rows, 154.6 MB)

========================================================================
  Sheet : '03PIC1023 PVLO_PVHI'
  Tag   : 03PIC1023   AlarmType: PVLO_PVHI   Output: 03PIC1023_PVLO_PVHI_combined_events.parquet
========================================================================
  Asset IDs : ['1A', '1D', '1E', '1F', '1I', '1L']
  Event tables loaded : 18
  ✓ Saved  03PIC1023_PVLO_PVHI_combined_events.parquet  (4,587,437 rows, 119.5 MB)

========================================================================
  Sheet : '03TIC_1145 PVLO'
  Tag   : 03TIC_1145   AlarmType: PVLO   Output: 03TIC_1145_PVLO_combined_events.parquet
========================================================================
  Asset IDs : ['1A', '1E', '1F', '1L']
  Event tables loaded : 12
  ✓ Saved  03TIC_1145_PVLO_combined_events.parquet  (4,401,453 rows, 113.4 MB)

========================================================================
  Sheet : '03LIC_1071 PVHI'
  Tag   : 03LIC_1071   AlarmType: PVHI   Output: 03LIC_1071_PVHI_combined_events.parquet
========================================================================
  Asset IDs : ['1A', '1E', '1F', '1H', '1I', '1K', '1L']
  Event tables loaded : 21
  ✓ Saved  03LIC_1071_PVHI_combined_events.parquet  (5,573,157 rows, 146.4 MB)

========================================================================
  Sheet : '03LIC_1016 PVLO_PVHI'
  Tag   : 03LIC_1016   AlarmType: PVLO_PVHI   Output: 03LIC_1016_PVLO_PVHI_combined_events.parquet
========================================================================
  Asset IDs : ['1A', '1E', '1F', '1L']
  Event tables loaded : 12
  ✓ Saved  03LIC_1016_PVLO_PVHI_combined_events.parquet  (4,401,453 rows, 113.4 MB)

========================================================================
  Sheet : '03TI_1081 PVHI'
  Tag   : 03TI_1081   AlarmType: PVHI   Output: 03TI_1081_PVHI_combined_events.parquet
========================================================================
  Asset IDs : ['1L']
  Event tables loaded : 3
  ✓ Saved  03TI_1081_PVHI_combined_events.parquet  (1,187,544 rows, 30.3 MB)

========================================================================
  Sheet : '03LIC_1094'
  Tag   : 03LIC_1094   AlarmType: None   Output: 03LIC_1094_combined_events.parquet
========================================================================
  [SKIP] Required columns (ASSET ID / DCS Tag Name) not found

========================================================================
  Sheet : '03PI_1814 PVHI'
  Tag   : 03PI_1814   AlarmType: PVHI   Output: 03PI_1814_PVHI_combined_events.parquet
========================================================================
  [SKIP] No valid ASSET IDs found in sheet

========================================================================
  Sheet : '03PIC_1013 PVLO'
  Tag   : 03PIC_1013   AlarmType: PVLO   Output: 03PIC_1013_PVLO_combined_events.parquet
========================================================================
  Asset IDs : ['1E', '1F', '1L']
  Event tables loaded : 9
  ✓ Saved  03PIC_1013_PVLO_combined_events.parquet  (1,637,937 rows, 43.0 MB)

========================================================================
  Sheet : '03TIC_1745A PVHI'
  Tag   : 03TIC_1745A   AlarmType: PVHI   Output: 03TIC_1745A_PVHI_combined_events.parquet
========================================================================
  Asset IDs : ['1G', '1H', '1N']
  Event tables loaded : 9
  ✓ Saved  03TIC_1745A_PVHI_combined_events.parquet  (923,134 rows, 24.3 MB)

========================================================================
  Sheet : '03LIC1608_PVLO'
  Tag   : 03LIC1608   AlarmType: PVLO   Output: 03LIC1608_PVLO_combined_events.parquet
========================================================================
  Asset IDs : ['1A', '1E', '1O']
  Event tables loaded : 9
  ✓ Saved  03LIC1608_PVLO_combined_events.parquet  (3,270,820 rows, 83.4 MB)

========================================================================
  Sheet : '03PI_1655_PVHI'
  Tag   : 03PI_1655   AlarmType: PVHI   Output: 03PI_1655_PVHI_combined_events.parquet
========================================================================
  Asset IDs : ['1E', '1F', '1O']
  Event tables loaded : 9
  ✓ Saved  03PI_1655_PVHI_combined_events.parquet  (708,824 rows, 20.6 MB)

========================================================================
  BATCH COMPLETE  —  19 sheets processed
========================================================================

,Sheet,Tag,AlarmType,Status,Rows,File
0,03TIC_1023 PVLO_PVHI,03TIC_1023,PVLO_PVHI,OK,4587437.0,03TIC_1023_PVLO_PVHI_combined_events.parquet
1,03TIC_1635 PVLO,03TIC_1635,PVLO,OK,3866251.0,03TIC_1635_PVLO_combined_events.parquet
2,03TIC_1009_PVLO,03TIC_1009,PVLO,OK,3874588.0,03TIC_1009_PVLO_combined_events.parquet
3,03TIC_1009_PVHI,03TIC_1009,PVHI,OK,3874588.0,03TIC_1009_PVHI_combined_events.parquet
4,03LIC_1619 PVLO_PVHI,03LIC_1619,PVLO_PVHI,OK,3021947.0,03LIC_1619_PVLO_PVHI_combined_events.parquet
5,03TIC_1635_PVHI,03TIC_1635,PVHI,OK,3866251.0,03TIC_1635_PVHI_combined_events.parquet
6,03FIC_1668 PVHI,03FIC_1668,PVHI,OK,4005637.0,03FIC_1668_PVHI_combined_events.parquet
7,03PIC_1104 PVHI,03PIC_1104,PVHI,OK,5925960.0,03PIC_1104_PVHI_combined_events.parquet
8,03PIC1023 PVLO_PVHI,03PIC1023,PVLO_PVHI,OK,4587437.0,03PIC1023_PVLO_PVHI_combined_events.parquet
9,03TIC_1145 PVLO,03TIC_1145,PVLO,OK,4401453.0,03TIC_1145_PVLO_combined_events.parquet
10,03LIC_1071 PVHI,03LIC_1071,PVHI,OK,5573157.0,03LIC_1071_PVHI_combined_events.parquet
11,03LIC_1016 PVLO_PVHI,03LIC_1016,PVLO_PVHI,OK,4401453.0,03LIC_1016_PVLO_PVHI_combined_events.parquet
12,03TI_1081 PVHI,03TI_1081,PVHI,OK,1187544.0,03TI_1081_PVHI_combined_events.parquet
13,03LIC_1094,03LIC_1094,None,SKIP (missing cols),NaN,None
14,03PI_1814 PVHI,03PI_1814,PVHI,SKIP (no assets),NaN,None
15,03PIC_1013 PVLO,03PIC_1013,PVLO,OK,1637937.0,03PIC_1013_PVLO_combined_events.parquet
16,03TIC_1745A PVHI,03TIC_1745A,PVHI,OK,923134.0,03TIC_1745A_PVHI_combined_events.parquet
17,03LIC1608_PVLO,03LIC1608,PVLO,OK,3270820.0,03LIC1608_PVLO_combined_events.parquet
18,03PI_1655_PVHI,03PI_1655,PVHI,OK,708824.0,03PI_1655_PVHI_combined_events.parquet